services:
  - type: web
    name: smart-travel-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: KHALTI_SECRET_KEY
        sync: false
      - key: KHALTI_MODE
        value: live
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
