const mongoose = require("mongoose");

const locationSeeds = [
  {
    key: "chitwan",
    name: "Chitwan",
    province: "Bagmati",
    district: "Chitwan",
    category: "Destination Hub",
    averageCost: 2200,
    latitude: 27.6236,
    longitude: 84.4294,
    description:
      "Chitwan is Nepal's leading lowland wildlife destination, known for jungle safaris, Tharu culture, wetlands, riverside sunsets, and nature-based short escapes.",
    image: "",
    images: [],
  },
  {
    key: "chitwan-national-park",
    parentKey: "chitwan",
    name: "Chitwan National Park",
    province: "Bagmati",
    district: "Chitwan",
    category: "Nature",
    averageCost: 2000,
    latitude: 27.5341,
    longitude: 84.4525,
    description:
      "Nepal's best-known jungle park with rhinos, crocodiles, birdlife, river habitats, and guided safari experiences around the Sauraha side.",
    image: "",
    images: [],
  },
  {
    key: "rapti-river-sauraha",
    parentKey: "chitwan",
    name: "Rapti River, Sauraha",
    province: "Bagmati",
    district: "Chitwan",
    category: "Nature",
    averageCost: 900,
    latitude: 27.5768,
    longitude: 84.4964,
    description:
      "The classic Sauraha riverside zone for canoeing, sunset walks, birdwatching, and gentle evening outings.",
    image: "",
    images: [],
  },
  {
    key: "sauraha-tharu-cultural-house",
    parentKey: "chitwan",
    name: "Sauraha Tharu Cultural House",
    province: "Bagmati",
    district: "Chitwan",
    category: "Cultural",
    averageCost: 300,
    latitude: 27.5779,
    longitude: 84.4957,
    description:
      "A popular cultural venue in Sauraha where visitors experience Tharu dance, music, and local storytelling in the evening.",
    image: "",
    images: [],
  },
  {
    key: "tharu-cultural-museum",
    parentKey: "chitwan",
    name: "Tharu Cultural Museum",
    province: "Bagmati",
    district: "Chitwan",
    category: "Museum",
    averageCost: 200,
    latitude: 27.5783,
    longitude: 84.4952,
    description:
      "A compact museum preserving Tharu tools, dress, architecture, and local heritage close to the Sauraha tourist area.",
    image: "",
    images: [],
  },
  {
    key: "elephant-breeding-center",
    parentKey: "chitwan",
    name: "Elephant Breeding Center",
    province: "Bagmati",
    district: "Chitwan",
    category: "Nature",
    averageCost: 150,
    latitude: 27.5855,
    longitude: 84.5045,
    description:
      "A conservation-centered stop where visitors can observe elephants and learn about breeding, rescue, and care practices.",
    image: "",
    images: [],
  },
  {
    key: "gharial-breeding-center",
    parentKey: "chitwan",
    name: "Gharial Breeding Center",
    province: "Bagmati",
    district: "Chitwan",
    category: "Nature",
    averageCost: 150,
    latitude: 27.593,
    longitude: 84.336,
    description:
      "A reptile conservation facility in the Kasara area focused on gharial breeding and awareness about river ecosystem protection.",
    image: "",
    images: [],
  },
  {
    key: "bishazari-tal",
    parentKey: "chitwan",
    name: "Bishazari Tal",
    province: "Bagmati",
    district: "Chitwan",
    category: "Lake",
    averageCost: 300,
    latitude: 27.6181,
    longitude: 84.4364,
    description:
      "A Ramsar-listed wetland lake system known for birdwatching, peaceful scenery, and short nature excursions near Bharatpur.",
    image: "",
    images: [],
  },
  {
    key: "kasara-visitor-area",
    parentKey: "chitwan",
    name: "Kasara Visitor Area",
    province: "Bagmati",
    district: "Chitwan",
    category: "Museum",
    averageCost: 300,
    latitude: 27.5865,
    longitude: 84.3395,
    description:
      "Historic park headquarters area used for visitor orientation, conservation interpretation, and nearby short nature walks.",
    image: "",
    images: [],
  },
  {
    key: "devghat-dham",
    parentKey: "chitwan",
    name: "Devghat Dham",
    province: "Bagmati",
    district: "Chitwan",
    category: "Temple",
    averageCost: 100,
    latitude: 27.7392,
    longitude: 84.4253,
    description:
      "A sacred river confluence and pilgrimage destination with temples, ashrams, ritual spaces, and a calm spiritual atmosphere.",
    image: "",
    images: [],
  },
  {
    key: "narayani-riverbank",
    parentKey: "chitwan",
    name: "Narayani Riverbank",
    province: "Bagmati",
    district: "Chitwan",
    category: "Nature",
    averageCost: 200,
    latitude: 27.6765,
    longitude: 84.432,
    description:
      "A Bharatpur riverside leisure area suited to evening walks, local food stops, and casual boating with broad river views.",
    image: "",
    images: [],
  },
  {
    key: "jalbire-jharana",
    parentKey: "chitwan",
    name: "Jalbire Jharana",
    province: "Bagmati",
    district: "Chitwan",
    category: "Nature",
    averageCost: 250,
    latitude: 27.8239,
    longitude: 84.5231,
    description:
      "A scenic waterfall stop in northern Chitwan visited for greenery, short hikes, and relaxed day trips from the city side.",
    image: "",
    images: [],
  },
  {
    key: "diyalo-bangala-park",
    parentKey: "chitwan",
    name: "Diyalo Bangala Park",
    province: "Bagmati",
    district: "Chitwan",
    category: "Cultural",
    averageCost: 100,
    latitude: 27.6751,
    longitude: 84.4423,
    description:
      "A relaxed urban park in Bharatpur that works well for short family visits, local atmosphere, and easy evening downtime.",
    image: "",
    images: [],
  },
];

const listingSeeds = [
  {
    type: "activity",
    title: "Chitwan Shared Jeep Safari",
    description: "Half-day safari drive searching for rhino, deer, birds, and grassland wildlife.",
    location: { name: "Chitwan National Park", address: "Sauraha Park Entry Area, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5747, lng: 84.4936 },
    pricePerUnit: 3500,
    capacity: 7,
    amenities: ["Nature guide", "Shared jeep", "Permit support"],
    rating: 4.8,
  },
  {
    type: "activity",
    title: "Chitwan Guided Jungle Walk",
    description: "Guided forest-edge walking experience focused on tracks, flora, and safe wildlife interpretation.",
    location: { name: "Chitwan National Park", address: "Sauraha Nature Trail, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5728, lng: 84.4914 },
    pricePerUnit: 1800,
    capacity: 10,
    amenities: ["Guide", "Safety briefing", "Walking route support"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Rapti River Canoe Safari",
    description: "Quiet river session with chances to see crocodiles, birds, and riverside wildlife.",
    location: { name: "Chitwan National Park", address: "Rapti Canoe Launch, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5763, lng: 84.4961 },
    pricePerUnit: 2200,
    capacity: 8,
    amenities: ["Life jackets", "Boatman", "Naturalist support"],
    rating: 4.8,
  },
  {
    type: "activity",
    title: "Rapti Sunset Canoe Ride",
    description: "Golden-hour canoe ride on the Rapti with soft light and calm river views.",
    location: { name: "Rapti River, Sauraha", address: "Sunset Point Jetty, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5772, lng: 84.4968 },
    pricePerUnit: 1800,
    capacity: 8,
    amenities: ["Life jackets", "Boatman", "Sunset timing"],
    rating: 4.8,
  },
  {
    type: "activity",
    title: "Rapti Riverside Sunset Walk",
    description: "Easy guided riverbank walk timed for Sauraha's most popular sunset hour.",
    location: { name: "Rapti River, Sauraha", address: "Riverside Walkway, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5775, lng: 84.4965 },
    pricePerUnit: 300,
    capacity: 20,
    amenities: ["Walkway access", "Guide", "Photo stops"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Rapti Evening Birdwatching",
    description: "Short dusk birding session around the riverbank with common wetland species.",
    location: { name: "Rapti River, Sauraha", address: "Rapti Birding Zone, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5769, lng: 84.4959 },
    pricePerUnit: 900,
    capacity: 10,
    amenities: ["Bird guide", "Binocular support", "Slow-paced outing"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Tharu Cultural Dance Show",
    description: "Traditional Tharu stick dance and music performance in the evening.",
    location: { name: "Sauraha Tharu Cultural House", address: "Cultural Hall, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5779, lng: 84.4957 },
    pricePerUnit: 250,
    capacity: 120,
    amenities: ["Stage seating", "Cultural performance", "Evening schedule"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Tharu Village Heritage Walk",
    description: "Short guided walk through nearby Tharu settlement and traditional homes.",
    location: { name: "Sauraha Tharu Cultural House", address: "Tharu Village Route, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5785, lng: 84.497 },
    pricePerUnit: 800,
    capacity: 12,
    amenities: ["Local guide", "Village route", "Cultural interpretation"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Tharu Storytelling Session",
    description: "A seated cultural session introducing local customs, dress, food, and festivals.",
    location: { name: "Sauraha Tharu Cultural House", address: "Community Hall, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5778, lng: 84.4955 },
    pricePerUnit: 500,
    capacity: 20,
    amenities: ["Seating", "Local host", "Interpreter support on request"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Tharu Museum Entry Tour",
    description: "Self-paced museum visit through Tharu artifacts, tools, and heritage displays.",
    location: { name: "Tharu Cultural Museum", address: "Museum Lane, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5783, lng: 84.4952 },
    pricePerUnit: 200,
    capacity: 25,
    amenities: ["Entry access", "Display halls", "Interpretive exhibits"],
    rating: 4.3,
  },
  {
    type: "activity",
    title: "Tharu Heritage Walkthrough",
    description: "Guided explanation of Tharu domestic life, farming tools, and local material culture.",
    location: { name: "Tharu Cultural Museum", address: "Museum Complex, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5781, lng: 84.4953 },
    pricePerUnit: 600,
    capacity: 12,
    amenities: ["Guide", "Museum access", "Heritage interpretation"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Traditional Costume Photo Session",
    description: "Light cultural add-on with costume props and museum courtyard photos.",
    location: { name: "Tharu Cultural Museum", address: "Museum Courtyard, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5784, lng: 84.4951 },
    pricePerUnit: 500,
    capacity: 8,
    amenities: ["Props", "Photo area", "Staff support"],
    rating: 4.2,
  },
  {
    type: "activity",
    title: "Elephant Conservation Visit",
    description: "Introductory educational visit explaining elephant breeding and care work.",
    location: { name: "Elephant Breeding Center", address: "Khorsor, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5855, lng: 84.5045 },
    pricePerUnit: 300,
    capacity: 20,
    amenities: ["Entry", "Guide", "Viewing areas"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Elephant Observation Tour",
    description: "Ethical observation-focused visit with time around enclosures and interpretation points.",
    location: { name: "Elephant Breeding Center", address: "Observation Zone, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5858, lng: 84.5041 },
    pricePerUnit: 500,
    capacity: 15,
    amenities: ["Guide", "Viewing platform", "Conservation briefing"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Elephant Photography Walk",
    description: "Soft-paced short outing for elephant and enclosure photography around the center.",
    location: { name: "Elephant Breeding Center", address: "Photo Route, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5851, lng: 84.5048 },
    pricePerUnit: 700,
    capacity: 8,
    amenities: ["Guide", "Photo stops", "Slow-paced route"],
    rating: 4.3,
  },
  {
    type: "activity",
    title: "Gharial Conservation Tour",
    description: "Educational stop focused on endangered gharials and river conservation work.",
    location: { name: "Gharial Breeding Center", address: "Kasara Conservation Area, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.593, lng: 84.336 },
    pricePerUnit: 400,
    capacity: 15,
    amenities: ["Entry", "Guide", "Interpretive displays"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Reptile Interpretation Visit",
    description: "Short learning session on gharials, mugger crocodiles, and river ecosystems.",
    location: { name: "Gharial Breeding Center", address: "Interpretation Area, Kasara, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5928, lng: 84.3363 },
    pricePerUnit: 300,
    capacity: 20,
    amenities: ["Guide", "Info boards", "Educational stop"],
    rating: 4.3,
  },
  {
    type: "activity",
    title: "Kasara Birdwatching Stop",
    description: "Birding add-on near riverine habitat around the breeding center area.",
    location: { name: "Gharial Breeding Center", address: "Kasara River Edge, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5924, lng: 84.3357 },
    pricePerUnit: 600,
    capacity: 10,
    amenities: ["Bird guide", "Binocular support", "Nature stop"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Bishazari Wetland Birding Tour",
    description: "Early or late-day birdwatching around the wetland fringe and reed habitat.",
    location: { name: "Bishazari Tal", address: "Bishazari Wetland Access, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.6181, lng: 84.4364 },
    pricePerUnit: 1500,
    capacity: 8,
    amenities: ["Bird guide", "Binocular support", "Wetland route"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Bishazari Nature Walk",
    description: "Gentle nature route around the lake area with interpretation of plants and wetland ecology.",
    location: { name: "Bishazari Tal", address: "Lake Trailhead, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.6176, lng: 84.4368 },
    pricePerUnit: 700,
    capacity: 12,
    amenities: ["Local guide", "Easy trail", "Nature interpretation"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Bishazari Photography Excursion",
    description: "A focused short outing for wetland landscape and bird photography.",
    location: { name: "Bishazari Tal", address: "Scenic View Edge, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.6186, lng: 84.4361 },
    pricePerUnit: 1000,
    capacity: 6,
    amenities: ["Guide", "Photo stops", "Scenic viewpoints"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Kasara Park History Tour",
    description: "A guided visit focused on park history, conservation milestones, and visitor orientation.",
    location: { name: "Kasara Visitor Area", address: "Kasara Headquarters Area, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5865, lng: 84.3395 },
    pricePerUnit: 500,
    capacity: 15,
    amenities: ["Guide", "Interpretation", "Orientation stop"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Kasara Visitor Briefing Session",
    description: "A short orientation for travelers interested in the wider Chitwan park system.",
    location: { name: "Kasara Visitor Area", address: "Visitor Briefing Hall, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5862, lng: 84.3397 },
    pricePerUnit: 250,
    capacity: 20,
    amenities: ["Maps", "Guide", "Visitor orientation"],
    rating: 4.2,
  },
  {
    type: "activity",
    title: "Kasara Forest Edge Nature Trail",
    description: "Short low-intensity walk near the headquarters area with guide support.",
    location: { name: "Kasara Visitor Area", address: "Kasara Trailhead, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5869, lng: 84.3392 },
    pricePerUnit: 600,
    capacity: 10,
    amenities: ["Guide", "Nature trail", "Easy walk"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Devghat Temple Circuit Visit",
    description: "Guided visit through key shrines and sacred spaces at the river confluence.",
    location: { name: "Devghat Dham", address: "Devghat Temple Area, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.7392, lng: 84.4253 },
    pricePerUnit: 500,
    capacity: 15,
    amenities: ["Guide", "Temple route", "Cultural interpretation"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Devghat Holy River Ritual Experience",
    description: "Observe or join simple riverside ritual practices in a respectful guided format.",
    location: { name: "Devghat Dham", address: "Devghat Ghat Area, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.739, lng: 84.4251 },
    pricePerUnit: 300,
    capacity: 20,
    amenities: ["Guide", "Ritual briefing", "Temple-side access"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Devghat Sunrise Pilgrimage Walk",
    description: "Quiet early morning walk linking river views, ashrams, and shrine spaces.",
    location: { name: "Devghat Dham", address: "Sunrise Walk Route, Devghat, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.7395, lng: 84.4256 },
    pricePerUnit: 400,
    capacity: 15,
    amenities: ["Guide", "Easy route", "Morning timing"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Narayani Riverside Evening Walk",
    description: "Easy local leisure walk with broad river views and relaxed city atmosphere.",
    location: { name: "Narayani Riverbank", address: "Pulchowk Riverfront, Bharatpur, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.6765, lng: 84.432 },
    pricePerUnit: 200,
    capacity: 25,
    amenities: ["Open riverfront", "Guide", "Photo stops"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Narayani Local Boat Ride",
    description: "Short recreational boating add-on on calmer river sections near Bharatpur.",
    location: { name: "Narayani Riverbank", address: "Bharatpur Boat Point, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.6762, lng: 84.4317 },
    pricePerUnit: 700,
    capacity: 6,
    amenities: ["Boat", "Life jackets", "Short river loop"],
    rating: 4.3,
  },
  {
    type: "activity",
    title: "Narayani Street Food Walk",
    description: "Guided evening tasting walk with simple local snacks near the riverside area.",
    location: { name: "Narayani Riverbank", address: "Riverfront Food Lane, Bharatpur, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.6769, lng: 84.4324 },
    pricePerUnit: 900,
    capacity: 10,
    amenities: ["Local guide", "Food stops", "Easy city walk"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Jalbire Waterfall Hike",
    description: "Day-hike style outing to the waterfall area through green hillside terrain.",
    location: { name: "Jalbire Jharana", address: "Jalbire Trail Start, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.8239, lng: 84.5231 },
    pricePerUnit: 1200,
    capacity: 10,
    amenities: ["Guide", "Trail support", "Nature route"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Jalbire Picnic Excursion",
    description: "Soft outdoor day trip ideal for students, small groups, and families.",
    location: { name: "Jalbire Jharana", address: "Jalbire Picnic Area, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.8235, lng: 84.5236 },
    pricePerUnit: 800,
    capacity: 12,
    amenities: ["Rest area", "Group outing", "Scenic stop"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Jalbire Scenic Photography Trip",
    description: "Short guided photography-focused outing around the waterfall and greenery.",
    location: { name: "Jalbire Jharana", address: "Jalbire View Area, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.8242, lng: 84.5227 },
    pricePerUnit: 900,
    capacity: 8,
    amenities: ["Guide", "Photo stops", "Landscape focus"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Diyalo Family Leisure Visit",
    description: "Simple family-friendly park outing with time for rest and local atmosphere.",
    location: { name: "Diyalo Bangala Park", address: "Diyalo Bangala, Bharatpur, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.6751, lng: 84.4423 },
    pricePerUnit: 100,
    capacity: 30,
    amenities: ["Open grounds", "Seating", "Family-friendly"],
    rating: 4.1,
  },
  {
    type: "activity",
    title: "Diyalo Morning Walk Session",
    description: "A short low-cost urban nature break for locals and travelers staying in Bharatpur.",
    location: { name: "Diyalo Bangala Park", address: "Park Walkway, Bharatpur, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.6754, lng: 84.4425 },
    pricePerUnit: 100,
    capacity: 25,
    amenities: ["Walking path", "Open park", "Easy access"],
    rating: 4.2,
  },
  {
    type: "activity",
    title: "Diyalo Outdoor Photo Stop",
    description: "Casual stop for portraits, local atmosphere, and light relaxation.",
    location: { name: "Diyalo Bangala Park", address: "Garden Edge, Bharatpur, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.6749, lng: 84.4421 },
    pricePerUnit: 150,
    capacity: 15,
    amenities: ["Landscaped area", "Quick stop", "Photo-friendly"],
    rating: 4.0,
  },
  {
    type: "hotel",
    title: "Barahi Jungle Lodge",
    description: "A premium Rapti-side jungle lodge built for higher-end safari stays, birding, and riverside downtime.",
    location: { name: "Chitwan National Park", address: "Meghauli, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5331, lng: 84.2222 },
    pricePerUnit: 29000,
    capacity: 2,
    amenities: ["Pool", "Spa", "Restaurant", "Nature guide", "Airport transfer"],
    rating: 4.8,
  },
  {
    type: "hotel",
    title: "Meghauli Serai",
    description: "Luxury safari retreat in Meghauli with refined rooms, nature access, and strong honeymoon appeal.",
    location: { name: "Chitwan National Park", address: "Meghauli, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5318, lng: 84.2215 },
    pricePerUnit: 42000,
    capacity: 2,
    amenities: ["Pool", "Spa", "Fine dining", "Safari desk", "River views"],
    rating: 4.9,
  },
  {
    type: "hotel",
    title: "Green Park Chitwan",
    description: "An upper-midscale Sauraha stay with pool, garden setting, and practical safari access.",
    location: { name: "Rapti River, Sauraha", address: "Tiger Point, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5788, lng: 84.4905 },
    pricePerUnit: 12000,
    capacity: 3,
    amenities: ["Pool", "Garden", "Restaurant", "Wi-Fi", "Safari booking"],
    rating: 4.6,
  },
  {
    type: "hotel",
    title: "Jungle Villa Resort",
    description: "A comfortable resort-style Sauraha stay suited to couples, families, and small tour groups.",
    location: { name: "Rapti River, Sauraha", address: "Sauraha, Ratnanagar, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5794, lng: 84.4917 },
    pricePerUnit: 14000,
    capacity: 3,
    amenities: ["Pool", "AC rooms", "Restaurant", "Shuttle", "Cultural program"],
    rating: 4.5,
  },
  {
    type: "hotel",
    title: "Landmark Forest Park",
    description: "A dependable full-service hotel close to the main Sauraha tourism corridor.",
    location: { name: "Rapti River, Sauraha", address: "Sauraha Main Road, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5771, lng: 84.4921 },
    pricePerUnit: 10000,
    capacity: 3,
    amenities: ["Pool", "Wi-Fi", "Restaurant", "Parking", "Tour desk"],
    rating: 4.4,
  },
  {
    type: "hotel",
    title: "Sauraha Resort",
    description: "A long-running Sauraha property with easy access to jungle and cultural activities.",
    location: { name: "Rapti River, Sauraha", address: "Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5782, lng: 84.4932 },
    pricePerUnit: 9000,
    capacity: 3,
    amenities: ["Garden", "AC", "Wi-Fi", "Restaurant", "Safari assistance"],
    rating: 4.4,
  },
  {
    type: "hotel",
    title: "Hotel Parkland",
    description: "Good-value resort option for wildlife visitors wanting comfort without luxury pricing.",
    location: { name: "Rapti River, Sauraha", address: "Sauraha-2, Ratnanagar, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5798, lng: 84.4943 },
    pricePerUnit: 8500,
    capacity: 3,
    amenities: ["Pool", "Bar", "Wi-Fi", "Parking", "Cultural evenings"],
    rating: 4.3,
  },
  {
    type: "hotel",
    title: "Hotel Seven Star",
    description: "A polished Bharatpur hotel suitable for family trips, city stays, and airport-linked arrivals.",
    location: { name: "Narayani Riverbank", address: "Bharatpur Height, Bharatpur, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.6832, lng: 84.4384 },
    pricePerUnit: 11000,
    capacity: 3,
    amenities: ["Conference hall", "Restaurant", "Gym", "Wi-Fi", "Parking"],
    rating: 4.4,
  },
  {
    type: "cafe",
    title: "Cafe de Safari",
    description: "A simple traveler-friendly Sauraha cafe popular for coffee, breakfast, and relaxed breaks between activities.",
    location: { name: "Rapti River, Sauraha", address: "Main Street, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5777, lng: 84.4938 },
    pricePerUnit: 450,
    capacity: 20,
    amenities: ["Coffee", "Breakfast", "Traveler seating"],
    rating: 4.3,
  },
  {
    type: "cafe",
    title: "Friends Cafe Sauraha",
    description: "Well-liked rooftop-style cafe serving coffee, brunch, and light meals close to the tourist strip.",
    location: { name: "Rapti River, Sauraha", address: "Hatti Chowk, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5773, lng: 84.4949 },
    pricePerUnit: 550,
    capacity: 22,
    amenities: ["Coffee", "Brunch", "Rooftop seating"],
    rating: 4.7,
  },
  {
    type: "cafe",
    title: "Art Cafe Sauraha",
    description: "An artisan-style cafe known for coffee, creative decor, and a calm atmosphere.",
    location: { name: "Rapti River, Sauraha", address: "Main Street Area, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5781, lng: 84.4944 },
    pricePerUnit: 600,
    capacity: 18,
    amenities: ["Coffee", "Light meals", "Creative ambiance"],
    rating: 4.8,
  },
  {
    type: "cafe",
    title: "Caffeophilia Bharatpur",
    description: "A modern coffee stop in Bharatpur suited to city-side travelers, meetings, and work-friendly breaks.",
    location: { name: "Narayani Riverbank", address: "Lions Chowk, Bharatpur, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.6788, lng: 84.4319 },
    pricePerUnit: 650,
    capacity: 24,
    amenities: ["Specialty coffee", "Indoor seating", "Work-friendly tables"],
    rating: 4.8,
  },
  {
    type: "restaurant",
    title: "KC's Restaurant and Bar",
    description: "A garden-style Sauraha restaurant serving Nepali, Indian, and continental dinners for safari visitors.",
    location: { name: "Rapti River, Sauraha", address: "Sauraha Main Road, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5774, lng: 84.4934 },
    pricePerUnit: 1200,
    capacity: 40,
    amenities: ["Indoor seating", "Bar", "Garden dining"],
    rating: 4.5,
  },
  {
    type: "restaurant",
    title: "Shantiko Kitchen",
    description: "A warm, sustainable-minded dining spot with strong traveler reviews and polished comfort food.",
    location: { name: "Rapti River, Sauraha", address: "Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5784, lng: 84.4941 },
    pricePerUnit: 1100,
    capacity: 28,
    amenities: ["Local cuisine", "Indoor seating", "Vegetarian-friendly"],
    rating: 4.8,
  },
  {
    type: "restaurant",
    title: "Greasy Spoon Restaurant",
    description: "Casual tourist-friendly restaurant popular for breakfast, pizza, and familiar comfort meals.",
    location: { name: "Rapti River, Sauraha", address: "Main Street, Sauraha, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5779, lng: 84.4943 },
    pricePerUnit: 1000,
    capacity: 30,
    amenities: ["Breakfast", "Indoor seating", "Multi-cuisine menu"],
    rating: 4.5,
  },
  {
    type: "restaurant",
    title: "Jalpeno Restaurant",
    description: "A popular Sauraha choice for travelers wanting Nepali, Mexican, and Italian options in one stop.",
    location: { name: "Rapti River, Sauraha", address: "Sauraha Main Street, Chitwan", district: "Chitwan", province: "Bagmati", lat: 27.5776, lng: 84.4946 },
    pricePerUnit: 1150,
    capacity: 32,
    amenities: ["Multi-cuisine", "Indoor seating", "Family-friendly"],
    rating: 4.4,
  },
];

const nearbyRecommendations = [
  { name: "Maula Kalika Temple, Gaindakot", distanceKm: 18, mainActivity: "Hill hike and temple visit" },
  { name: "Shashwat Dham, Devchuli", distanceKm: 45, mainActivity: "Spiritual tour and garden walk" },
  { name: "Amaltari, Nawalpur", distanceKm: 55, mainActivity: "Jeep safari and canoeing" },
  { name: "Balmiki Ashram", distanceKm: 95, mainActivity: "Pilgrimage visit and boat access" },
  { name: "Bandipur", distanceKm: 80, mainActivity: "Heritage walk and sunrise viewpoint" },
];

function buildChitwanSeed(createdBy) {
  if (!createdBy) {
    throw new Error("buildChitwanSeed(createdBy) requires a valid user id for Listing.createdBy");
  }

  const locationIdMap = new Map();

  const locations = locationSeeds.map((item) => {
    const _id = new mongoose.Types.ObjectId();
    locationIdMap.set(item.key, _id);
    return {
      _id,
      name: item.name,
      province: item.province,
      district: item.district,
      parentLocationId: null,
      description: item.description,
      category: item.category,
      averageCost: item.averageCost,
      image: item.image || "",
      images: item.images || [],
      latitude: item.latitude,
      longitude: item.longitude,
    };
  });

  for (const location of locations) {
    const seed = locationSeeds.find((item) => item.name === location.name);
    if (seed?.parentKey) {
      location.parentLocationId = locationIdMap.get(seed.parentKey) || null;
    }
  }

  const listings = listingSeeds.map((item) => ({
    type: item.type,
    title: item.title,
    description: item.description,
    location: item.location,
    pricePerUnit: item.pricePerUnit,
    capacity: item.capacity,
    amenities: item.amenities,
    photos: item.photos || [],
    rating: item.rating,
    reviews: [],
    isActive: true,
    createdBy,
  }));

  return {
    locations,
    listings,
    nearbyRecommendations,
  };
}

module.exports = {
  locationSeeds,
  listingSeeds,
  nearbyRecommendations,
  buildChitwanSeed,
};
