const tripPackageSeeds = [
  {
    title: "Chitwan Wildlife Escape",
    slug: "chitwan-wildlife-escape",
    shortDescription:
      "A compact Chitwan safari package with classic riverside moments, wildlife activities, and a cultural evening.",
    description:
      "This package is designed for travelers who want a clean and practical Chitwan introduction over a short stay. It combines Sauraha arrival, Rapti sunset atmosphere, a shared jeep safari, and a Tharu cultural evening into one easy booking flow.",
    location: "Chitwan",
    region: "Bagmati Province",
    pickupCity: "Bharatpur Airport / Sauraha Bus Stop",
    dropoffCity: "Bharatpur Airport / Sauraha Bus Stop",
    startDate: "2026-09-18",
    endDate: "2026-09-19",
    basePrice: 10200,
    discountPrice: 9500,
    rating: 4.6,
    currency: "NPR",
    capacity: 12,
    minGuests: 1,
    maxGuests: 12,
    coverImage: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1400&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80",
    ],
    videoUrl: "",
    included: [
      "1 night hotel stay in Sauraha",
      "Breakfast and dinner",
      "Pickup and drop from Bharatpur or Sauraha bus stop",
      "Rapti sunset walk",
      "Shared jeep safari",
      "Tharu cultural show",
      "Local trip coordination",
    ],
    excluded: [
      "Lunch and personal snacks",
      "Travel insurance",
      "Camera or premium guide add-ons",
      "Personal shopping expenses",
    ],
    highlights: [
      "Sauraha sunset atmosphere",
      "Rhino-focused jeep safari",
      "Tharu cultural performance",
      "Easy short-trip format",
    ],
    bestSeason: "October to March",
    difficulty: "Easy",
    tripType: "Wildlife and Culture Short Break",
    cancellationPolicy:
      "Free cancellation up to 5 days before departure. 25% charge within 48 hours. No refund for same-day cancellation.",
    paymentPolicy:
      "25% advance required to confirm. Remaining amount payable before safari departure.",
    faqs: [
      {
        question: "Is this package suitable for first-time Chitwan visitors?",
        answer:
          "Yes. It is built as a simple first stay covering the most recognizable Chitwan experiences.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Arrival, riverside sunset, and cultural evening",
        summary:
          "Arrive in Sauraha, settle into your hotel, enjoy a Rapti riverside sunset outing, and attend a Tharu cultural show in the evening.",
        hotelTitle: "Sauraha Resort",
        meals: ["Welcome drink", "Dinner"],
        transport: "Pickup transfer from Bharatpur or Sauraha stop",
        altitude: "150 m",
        notes: "Ideal for a soft first day after road travel.",
        image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
        activities: [
          { listingTitle: "Rapti Riverside Sunset Walk", notes: "Popular first-evening introduction to Sauraha." },
          { listingTitle: "Tharu Cultural Dance Show", notes: "Evening performance after dinner." },
        ],
      },
      {
        dayNumber: 2,
        title: "Morning safari and departure",
        summary:
          "Start early for a shared jeep safari inside the Chitwan area, return for breakfast, and check out for departure.",
        hotelTitle: "Sauraha Resort",
        meals: ["Breakfast"],
        transport: "Shared safari vehicle and departure transfer",
        altitude: "150 m",
        notes: "Carry neutral-colored clothing for the safari.",
        image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
        activities: [
          { listingTitle: "Chitwan Shared Jeep Safari", notes: "Early morning departure for stronger wildlife chances." },
        ],
      },
    ],
    addOnTitles: ["Rapti Sunset Canoe Ride", "Tharu Museum Entry Tour", "KC's Restaurant and Bar"],
    isFeatured: true,
    isActive: true,
  },
  {
    title: "Classic Chitwan Safari and Culture",
    slug: "classic-chitwan-safari-and-culture",
    shortDescription:
      "A balanced Chitwan package blending wildlife activities, canoeing, village culture, and a comfortable Sauraha stay.",
    description:
      "This package is a strong all-round Chitwan choice for domestic and international travelers who want both safari and culture. It combines Rapti canoeing, jungle walking, jeep safari, museum time, and Tharu cultural programming without making the trip feel rushed.",
    location: "Chitwan",
    region: "Bagmati Province",
    pickupCity: "Bharatpur Airport / Sauraha Bus Stop",
    dropoffCity: "Bharatpur Airport / Sauraha Bus Stop",
    startDate: "2026-10-10",
    endDate: "2026-10-12",
    basePrice: 17800,
    discountPrice: 16500,
    rating: 4.7,
    currency: "NPR",
    capacity: 14,
    minGuests: 2,
    maxGuests: 14,
    coverImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1400&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1473773508845-188df298d2d1?auto=format&fit=crop&w=1200&q=80",
    ],
    videoUrl: "",
    included: [
      "2 nights hotel stay in Sauraha",
      "Daily breakfast and 2 dinners",
      "Pickup and drop transfer",
      "Rapti canoe safari",
      "Guided jungle walk",
      "Shared jeep safari",
      "Tharu cultural show and museum visit",
      "Local trip coordinator support",
    ],
    excluded: ["Lunch", "Travel insurance", "Alcoholic beverages", "Optional private safari upgrade"],
    highlights: ["Rapti canoe safari", "Jungle walking experience", "Evening Tharu culture", "Well-rounded Chitwan flow"],
    bestSeason: "September to April",
    difficulty: "Easy to Moderate",
    tripType: "Wildlife and Cultural Explorer",
    cancellationPolicy:
      "Free cancellation up to 7 days before departure. 30% charge within 72 hours.",
    paymentPolicy:
      "30% advance required to confirm. Remaining balance payable at hotel check-in.",
    faqs: [
      {
        question: "Does this package include both wildlife and cultural activities?",
        answer:
          "Yes. It is designed specifically to balance safari experiences with local cultural experiences in Sauraha.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Arrival and Sauraha orientation",
        summary:
          "Arrive in Sauraha, check in, enjoy a riverside walk, and settle into the safari setting before dinner.",
        hotelTitle: "Green Park Chitwan",
        meals: ["Welcome drink", "Dinner"],
        transport: "Pickup transfer",
        altitude: "150 m",
        notes: "A calm arrival day with light movement only.",
        image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80",
        activities: [{ listingTitle: "Rapti Riverside Sunset Walk", notes: "Soft evening introduction to Chitwan." }],
      },
      {
        dayNumber: 2,
        title: "River safari and jungle day",
        summary:
          "Begin with a canoe safari, continue with a guided jungle walk, and later head out for a shared jeep safari before the cultural evening.",
        hotelTitle: "Green Park Chitwan",
        meals: ["Breakfast", "Dinner"],
        transport: "Shared safari transport",
        altitude: "150 m",
        notes: "Carry binoculars if available for birds and riverside wildlife.",
        image: "https://images.unsplash.com/photo-1466721591366-2d5fba72006d?auto=format&fit=crop&w=1200&q=80",
        activities: [
          { listingTitle: "Rapti River Canoe Safari", notes: "Morning wildlife-friendly river session." },
          { listingTitle: "Chitwan Guided Jungle Walk", notes: "Guided walk after the canoe outing." },
          { listingTitle: "Chitwan Shared Jeep Safari", notes: "Afternoon safari through the park zone." },
          { listingTitle: "Tharu Cultural Dance Show", notes: "Evening performance after dinner." },
        ],
      },
      {
        dayNumber: 3,
        title: "Museum visit and departure",
        summary:
          "After breakfast, visit the Tharu museum for heritage context and then transfer out for departure.",
        hotelTitle: "Green Park Chitwan",
        meals: ["Breakfast"],
        transport: "Private departure transfer",
        altitude: "150 m",
        notes: "Good fit for bus or airport departures after late morning.",
        image: "https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=1200&q=80",
        activities: [{ listingTitle: "Tharu Heritage Walkthrough", notes: "Cultural wrap-up before leaving Chitwan." }],
      },
    ],
    addOnTitles: ["Elephant Observation Tour", "Shantiko Kitchen", "Friends Cafe Sauraha"],
    isFeatured: true,
    isActive: true,
  },
  {
    title: "Chitwan Birding and Wetlands Explorer",
    slug: "chitwan-birding-and-wetlands-explorer",
    shortDescription:
      "A nature-focused Chitwan package built around wetland birding, river habitats, and slower wildlife observation.",
    description:
      "This itinerary is designed for birdwatchers, nature photographers, and travelers who prefer quieter wildlife experiences. It brings together Bishazari wetland birding, Rapti river sessions, Kasara interpretation, and gentle nature routes over four days.",
    location: "Chitwan",
    region: "Bagmati Province",
    pickupCity: "Bharatpur Airport / Bharatpur Bus Park",
    dropoffCity: "Bharatpur Airport / Bharatpur Bus Park",
    startDate: "2026-11-05",
    endDate: "2026-11-08",
    basePrice: 24500,
    discountPrice: 22500,
    rating: 4.8,
    currency: "NPR",
    capacity: 8,
    minGuests: 1,
    maxGuests: 8,
    coverImage: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1400&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1456926631375-92c8ce872def?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1473773508845-188df298d2d1?auto=format&fit=crop&w=1200&q=80",
    ],
    videoUrl: "",
    included: [
      "3 nights hotel stay",
      "Daily breakfast",
      "Pickup and drop transfer",
      "Bishazari birding sessions",
      "Rapti birdwatching outing",
      "Kasara visitor area visit",
      "Gharial conservation center stop",
      "Bird guide and binocular support",
    ],
    excluded: [
      "Lunch and dinner",
      "Travel insurance",
      "Professional photography gear hire",
      "Private vehicle upgrade unless selected",
    ],
    highlights: ["Wetland birding at Bishazari", "Rapti river ecology", "Kasara interpretation", "Slow-paced nature photography"],
    bestSeason: "October to February",
    difficulty: "Easy",
    tripType: "Birding and Nature Photography",
    cancellationPolicy:
      "Free cancellation up to 7 days before travel. 30% charge within 72 hours.",
    paymentPolicy:
      "30% advance payment required to confirm. Remaining amount due before Day 2 activities.",
    faqs: [
      {
        question: "Is this package suitable for serious birders?",
        answer:
          "Yes. The itinerary includes early wetland sessions and slower pacing that works well for birdwatching and photography.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Arrival and riverside birding introduction",
        summary:
          "Arrive in Chitwan, settle into your hotel, and begin with a light Rapti-side evening birdwatching session.",
        hotelTitle: "Hotel Seven Star",
        meals: ["Welcome drink"],
        transport: "Pickup transfer",
        altitude: "208 m",
        notes: "A city-based start works well for Bharatpur arrivals.",
        image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
        activities: [{ listingTitle: "Rapti Evening Birdwatching", notes: "Short introduction to common wetland species." }],
      },
      {
        dayNumber: 2,
        title: "Bishazari wetland focus",
        summary:
          "Head out early for the Bishazari wetland birding route, continue with a nature walk, and wrap with a photography-focused stop.",
        hotelTitle: "Hotel Seven Star",
        meals: ["Breakfast"],
        transport: "Private birding vehicle",
        altitude: "208 m",
        notes: "Early wake-up recommended for best species activity.",
        image: "https://images.unsplash.com/photo-1456926631375-92c8ce872def?auto=format&fit=crop&w=1200&q=80",
        activities: [
          { listingTitle: "Bishazari Wetland Birding Tour", notes: "Primary birding session of the itinerary." },
          { listingTitle: "Bishazari Nature Walk", notes: "Follow-up route after the core birding window." },
          { listingTitle: "Bishazari Photography Excursion", notes: "Best suited to long-lens and landscape work." },
        ],
      },
      {
        dayNumber: 3,
        title: "Kasara and conservation route",
        summary:
          "Visit the Kasara area for park interpretation, then continue to the gharial conservation center and nearby birding stop.",
        hotelTitle: "Hotel Seven Star",
        meals: ["Breakfast"],
        transport: "Private nature transfer",
        altitude: "208 m",
        notes: "Good educational day for wildlife-focused travelers.",
        image: "https://images.unsplash.com/photo-1466721591366-2d5fba72006d?auto=format&fit=crop&w=1200&q=80",
        activities: [
          { listingTitle: "Kasara Park History Tour", notes: "Context-setting stop before deeper conservation visits." },
          { listingTitle: "Gharial Conservation Tour", notes: "Main reptile conservation visit." },
          { listingTitle: "Kasara Birdwatching Stop", notes: "Short habitat-based add-on." },
        ],
      },
      {
        dayNumber: 4,
        title: "Easy city-side close and departure",
        summary:
          "Enjoy a relaxed breakfast, a short Narayani riverside stop if time allows, and depart from Chitwan.",
        hotelTitle: "Hotel Seven Star",
        meals: ["Breakfast"],
        transport: "Departure transfer",
        altitude: "208 m",
        notes: "Departure timing can be adjusted based on bus or flight schedule.",
        image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
        activities: [{ listingTitle: "Narayani Riverside Evening Walk", notes: "Can be shifted to a morning riverside stop as needed." }],
      },
    ],
    addOnTitles: ["Caffeophilia Bharatpur", "Narayani Street Food Walk", "Jalbire Scenic Photography Trip"],
    isFeatured: true,
    isActive: true,
  },
  {
    title: "Chitwan Family Leisure Trip",
    slug: "chitwan-family-leisure-trip",
    shortDescription:
      "A softer Chitwan itinerary for families with manageable safari activities, cultural learning, and easy sightseeing.",
    description:
      "This trip is designed for families and mixed-age groups who want Chitwan without an intense pace. It combines a comfortable stay, one safari drive, museum and elephant-center visits, and a relaxed Bharatpur or Sauraha rhythm.",
    location: "Chitwan",
    region: "Bagmati Province",
    pickupCity: "Bharatpur Airport / Sauraha Bus Stop",
    dropoffCity: "Bharatpur Airport / Sauraha Bus Stop",
    startDate: "2026-12-12",
    endDate: "2026-12-14",
    basePrice: 15800,
    discountPrice: 14500,
    rating: 4.5,
    currency: "NPR",
    capacity: 16,
    minGuests: 2,
    maxGuests: 16,
    coverImage: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1400&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1466721591366-2d5fba72006d?auto=format&fit=crop&w=1200&q=80",
    ],
    videoUrl: "",
    included: [
      "2 nights family-friendly hotel stay",
      "Breakfast and dinner",
      "Pickup and drop transfer",
      "Shared jeep safari",
      "Elephant conservation center visit",
      "Tharu museum visit",
      "Cultural evening",
      "Family trip coordination",
    ],
    excluded: ["Lunch", "Insurance", "Adventure-heavy add-ons", "Personal shopping and snacks"],
    highlights: ["Family-friendly pace", "Wildlife introduction", "Elephant and museum visits", "Evening culture program"],
    bestSeason: "September to April",
    difficulty: "Easy",
    tripType: "Family Leisure and Wildlife",
    cancellationPolicy:
      "Free cancellation up to 5 days before travel. 25% charge within 48 hours.",
    paymentPolicy:
      "25% advance payment required. Remaining amount due at hotel check-in.",
    faqs: [
      {
        question: "Is this package suitable for children and older family members?",
        answer:
          "Yes. The itinerary is intentionally soft-paced and avoids strenuous walks or very early adventure-heavy departures.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Arrival and relaxed riverside evening",
        summary:
          "Arrive in Chitwan, check in, and enjoy a calm Rapti riverside evening before dinner.",
        hotelTitle: "Landmark Forest Park",
        meals: ["Welcome drink", "Dinner"],
        transport: "Private family transfer",
        altitude: "150 m",
        notes: "A soft opening day designed for mixed-age comfort.",
        image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
        activities: [{ listingTitle: "Rapti Riverside Sunset Walk", notes: "Low-effort evening outing for the whole family." }],
      },
      {
        dayNumber: 2,
        title: "Safari and family learning day",
        summary:
          "Enjoy a shared jeep safari in the morning, then continue with the elephant breeding center and an evening cultural show.",
        hotelTitle: "Landmark Forest Park",
        meals: ["Breakfast", "Dinner"],
        transport: "Shared safari vehicle",
        altitude: "150 m",
        notes: "A balanced day with wildlife and educational stops.",
        image: "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1200&q=80",
        activities: [
          { listingTitle: "Chitwan Shared Jeep Safari", notes: "Main family wildlife experience." },
          { listingTitle: "Elephant Conservation Visit", notes: "Educational and child-friendly." },
          { listingTitle: "Tharu Cultural Dance Show", notes: "Evening entertainment with local culture." },
        ],
      },
      {
        dayNumber: 3,
        title: "Museum stop and departure",
        summary:
          "Visit the Tharu museum after breakfast, then head out for your departure transfer.",
        hotelTitle: "Landmark Forest Park",
        meals: ["Breakfast"],
        transport: "Private departure transfer",
        altitude: "150 m",
        notes: "Easy final morning with minimal travel pressure.",
        image: "https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=1200&q=80",
        activities: [{ listingTitle: "Tharu Museum Entry Tour", notes: "Simple final stop for culture and heritage context." }],
      },
    ],
    addOnTitles: ["Cafe de Safari", "Traditional Costume Photo Session", "Narayani Local Boat Ride"],
    isFeatured: false,
    isActive: true,
  },
  {
    title: "Luxury Meghauli Jungle Retreat",
    slug: "luxury-meghauli-jungle-retreat",
    shortDescription:
      "A premium Chitwan retreat with luxury lodge comfort, private wildlife experiences, and slower riverside downtime.",
    description:
      "This package is built for couples, premium travelers, and special-occasion guests who want Chitwan with more privacy and comfort. It combines a luxury Meghauli lodge, private safari flow, birding, canoeing, and relaxed time at the property.",
    location: "Chitwan",
    region: "Bagmati Province",
    pickupCity: "Bharatpur Airport",
    dropoffCity: "Bharatpur Airport",
    startDate: "2027-01-16",
    endDate: "2027-01-19",
    basePrice: 45000,
    discountPrice: 42000,
    rating: 4.9,
    currency: "NPR",
    capacity: 6,
    minGuests: 2,
    maxGuests: 6,
    coverImage: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1400&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1493558103817-58b2924bce98?auto=format&fit=crop&w=1200&q=80",
    ],
    videoUrl: "",
    included: [
      "3 nights luxury lodge stay",
      "All meals",
      "Private airport transfer",
      "Private jeep safari",
      "Private river canoe session",
      "Birding support",
      "Lodge leisure time and premium trip coordination",
    ],
    excluded: [
      "Alcoholic beverages unless included by lodge package",
      "Travel insurance",
      "Personal wellness treatments",
      "Professional photography services",
    ],
    highlights: ["Luxury Meghauli stay", "Private safari format", "River and birding experiences", "Premium slow-travel atmosphere"],
    bestSeason: "October to March",
    difficulty: "Easy",
    tripType: "Luxury Wildlife Retreat",
    cancellationPolicy:
      "Free cancellation up to 10 days before departure. 35% charge within 5 days. No refund within 24 hours.",
    paymentPolicy:
      "40% advance required to confirm. Remaining balance due 5 days before arrival.",
    faqs: [
      {
        question: "Is this package suitable for honeymoon or anniversary trips?",
        answer:
          "Yes. It is intentionally designed around privacy, upgraded lodge comfort, and premium safari pacing.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Arrival in Meghauli and riverside unwind",
        summary:
          "Transfer from Bharatpur to Meghauli, settle into the lodge, and enjoy a slow riverside evening with premium service.",
        hotelTitle: "Meghauli Serai",
        meals: ["Lunch", "Dinner"],
        transport: "Private airport transfer",
        altitude: "150 m",
        notes: "This first day is intentionally light and restorative.",
        image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
        activities: [],
      },
      {
        dayNumber: 2,
        title: "Private safari and lodge leisure",
        summary:
          "Head out for a private jeep safari in the morning, then return for a relaxed afternoon with lodge downtime.",
        hotelTitle: "Meghauli Serai",
        meals: ["Breakfast", "Lunch", "Dinner"],
        transport: "Private safari jeep",
        altitude: "150 m",
        notes: "Best suited to travelers who enjoy comfort between outings.",
        image: "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1200&q=80",
        activities: [{ listingTitle: "Chitwan Shared Jeep Safari", notes: "Operated as a private-format safari under the package arrangement." }],
      },
      {
        dayNumber: 3,
        title: "River session and birding",
        summary:
          "Enjoy a calmer day with a river canoe outing, selective birdwatching, and time back at the lodge.",
        hotelTitle: "Meghauli Serai",
        meals: ["Breakfast", "Lunch", "Dinner"],
        transport: "Private lodge activity transfer",
        altitude: "150 m",
        notes: "Photography-friendly day with slower pacing.",
        image: "https://images.unsplash.com/photo-1456926631375-92c8ce872def?auto=format&fit=crop&w=1200&q=80",
        activities: [
          { listingTitle: "Rapti River Canoe Safari", notes: "Private timing arranged by lodge coordination." },
          { listingTitle: "Rapti Evening Birdwatching", notes: "Flexible birding stop based on daylight and season." },
        ],
      },
      {
        dayNumber: 4,
        title: "Breakfast and departure",
        summary:
          "Wrap up with a relaxed breakfast and transfer back to Bharatpur for departure.",
        hotelTitle: "Meghauli Serai",
        meals: ["Breakfast"],
        transport: "Private departure transfer",
        altitude: "150 m",
        notes: "Late checkout may be possible depending on availability.",
        image: "https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=1200&q=80",
        activities: [],
      },
    ],
    addOnTitles: ["Barahi Jungle Lodge", "Caffeophilia Bharatpur", "Narayani Street Food Walk"],
    isFeatured: true,
    isActive: true,
  },
];

module.exports = {
  tripPackageSeeds,
};
