const locationSeeds = [
  {
    key: "kathmandu",
    name: "Kathmandu",
    province: "Bagmati",
    district: "Kathmandu",
    category: "Destination Hub",
    averageCost: 2800,
    latitude: 27.7172,
    longitude: 85.324,
    description:
      "Kathmandu is Nepal's historic capital, known for UNESCO heritage sites, temple squares, monasteries, museums, old markets, and city-edge hill escapes.",
    image: "",
    images: [],
  },
  {
    key: "swayambhunath-stupa",
    parentKey: "kathmandu",
    name: "Swayambhunath Stupa",
    province: "Bagmati",
    district: "Kathmandu",
    category: "Cultural",
    averageCost: 300,
    latitude: 27.7149,
    longitude: 85.29,
    description:
      "A historic Buddhist complex on a hilltop with valley views, shrines, prayer wheels, and one of Kathmandu's most iconic panoramas.",
    image: "",
    images: [],
  },
  {
    key: "pashupatinath-temple",
    parentKey: "kathmandu",
    name: "Pashupatinath Temple",
    province: "Bagmati",
    district: "Kathmandu",
    category: "Temple",
    averageCost: 1000,
    latitude: 27.7104,
    longitude: 85.3488,
    description:
      "Nepal's most important Shiva temple complex on the Bagmati River and a major pilgrimage destination.",
    image: "",
    images: [],
  },
  {
    key: "boudhanath-stupa",
    parentKey: "kathmandu",
    name: "Boudhanath Stupa",
    province: "Bagmati",
    district: "Kathmandu",
    category: "Cultural",
    averageCost: 400,
    latitude: 27.7215,
    longitude: 85.362,
    description:
      "A major Tibetan Buddhist landmark with monasteries, rooftop cafes, and one of the world's largest stupas.",
    image: "",
    images: [],
  },
  {
    key: "kathmandu-durbar-square",
    parentKey: "kathmandu",
    name: "Kathmandu Durbar Square",
    province: "Bagmati",
    district: "Kathmandu",
    category: "Cultural",
    averageCost: 1000,
    latitude: 27.7049,
    longitude: 85.3075,
    description:
      "UNESCO-listed royal square filled with temples, courtyards, and classic Newar architecture in the old city center.",
    image: "",
    images: [],
  },
  {
    key: "hanuman-dhoka-palace",
    parentKey: "kathmandu",
    name: "Hanuman Dhoka Palace",
    province: "Bagmati",
    district: "Kathmandu",
    category: "Museum",
    averageCost: 800,
    latitude: 27.7048,
    longitude: 85.3076,
    description:
      "Historic palace complex inside Kathmandu Durbar Square with museum galleries and royal courtyards.",
    image: "",
    images: [],
  },
  {
    key: "garden-of-dreams",
    parentKey: "kathmandu",
    name: "Garden of Dreams",
    province: "Bagmati",
    district: "Kathmandu",
    category: "Nature",
    averageCost: 400,
    latitude: 27.7134,
    longitude: 85.3156,
    description:
      "A restored neo-classical garden near Thamel, ideal for short breaks, photography, and relaxed city downtime.",
    image: "",
    images: [],
  },
  {
    key: "narayanhiti-palace-museum",
    parentKey: "kathmandu",
    name: "Narayanhiti Palace Museum",
    province: "Bagmati",
    district: "Kathmandu",
    category: "Museum",
    averageCost: 1000,
    latitude: 27.7173,
    longitude: 85.3217,
    description:
      "Former royal palace turned museum with reception halls, state rooms, and modern political history exhibits.",
    image: "",
    images: [],
  },
  {
    key: "budhanilkantha-temple",
    parentKey: "kathmandu",
    name: "Budhanilkantha Temple",
    province: "Bagmati",
    district: "Kathmandu",
    category: "Temple",
    averageCost: 300,
    latitude: 27.7807,
    longitude: 85.3672,
    description:
      "Open-air Vishnu shrine famous for its reclining stone deity resting in a sacred pond.",
    image: "",
    images: [],
  },
  {
    key: "chandragiri-hills",
    parentKey: "kathmandu",
    name: "Chandragiri Hills",
    province: "Bagmati",
    district: "Kathmandu",
    category: "Viewpoint",
    averageCost: 2500,
    latitude: 27.6738,
    longitude: 85.2057,
    description:
      "Hill destination with cable car access, mountain viewpoints, and temple visits above the valley.",
    image: "",
    images: [],
  },
  {
    key: "shivapuri-nagarjun-national-park",
    parentKey: "kathmandu",
    name: "Shivapuri Nagarjun National Park",
    province: "Bagmati",
    district: "Kathmandu",
    category: "Nature",
    averageCost: 1200,
    latitude: 27.817,
    longitude: 85.384,
    description:
      "Protected forest north of Kathmandu with hiking routes, birdlife, and cool hill air close to the city.",
    image: "",
    images: [],
  },
  {
    key: "kopan-monastery",
    parentKey: "kathmandu",
    name: "Kopan Monastery",
    province: "Bagmati",
    district: "Kathmandu",
    category: "Cultural",
    averageCost: 500,
    latitude: 27.7425,
    longitude: 85.3679,
    description:
      "A peaceful monastery on a hill with meditation culture, quiet surroundings, and city-edge views.",
    image: "",
    images: [],
  },
  {
    key: "asan-bazaar",
    parentKey: "kathmandu",
    name: "Asan Bazaar",
    province: "Bagmati",
    district: "Kathmandu",
    category: "Cultural",
    averageCost: 500,
    latitude: 27.7076,
    longitude: 85.3126,
    description:
      "Dense historic market square known for food walks, local trade, festivals, and everyday old-city life.",
    image: "",
    images: [],
  },
];

const listingSeeds = [
  {
    type: "activity",
    title: "Swayambhunath Heritage Walk",
    description: "Guided cultural walk around shrines, stairways, and monkey temple viewpoints.",
    location: { name: "Swayambhunath Stupa", address: "Swayambhunath Hill, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7149, lng: 85.29 },
    pricePerUnit: 700,
    capacity: 15,
    amenities: ["Guide", "Heritage route", "Viewpoint stops"],
    rating: 4.8,
  },
  {
    type: "activity",
    title: "Swayambhunath Sunrise View",
    description: "Early-morning city and valley viewpoint session from the stupa hill.",
    location: { name: "Swayambhunath Stupa", address: "Swayambhunath Viewpoint, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7152, lng: 85.2895 },
    pricePerUnit: 300,
    capacity: 20,
    amenities: ["View deck", "Early timing", "Photo stop"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Prayer Flag and Monastery Tour",
    description: "Short interpretive tour through shrine spaces and monastery surroundings.",
    location: { name: "Swayambhunath Stupa", address: "Swayambhunath Complex, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7147, lng: 85.2902 },
    pricePerUnit: 900,
    capacity: 10,
    amenities: ["Guide", "Monastery stop", "Photo points"],
    rating: 4.6,
  },

  {
    type: "activity",
    title: "Pashupatinath Darshan Circuit",
    description: "Classic temple complex visit with shrine and riverfront orientation.",
    location: { name: "Pashupatinath Temple", address: "Pashupatinath Complex, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7104, lng: 85.3488 },
    pricePerUnit: 1000,
    capacity: 25,
    amenities: ["Guide", "Temple access", "Cultural briefing"],
    rating: 4.8,
  },
  {
    type: "activity",
    title: "Bagmati Aarati Viewing",
    description: "Attend the evening devotional ritual along the river.",
    location: { name: "Pashupatinath Temple", address: "Arya Ghat Area, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7108, lng: 85.3493 },
    pricePerUnit: 500,
    capacity: 30,
    amenities: ["Evening slot", "Guide optional", "Riverfront view"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Hindu Heritage Tour",
    description: "Interpretive heritage tour focused on ritual, architecture, and sacred geography.",
    location: { name: "Pashupatinath Temple", address: "Pashupatinath Heritage Zone, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7111, lng: 85.3481 },
    pricePerUnit: 1500,
    capacity: 12,
    amenities: ["Local guide", "Temple history", "Riverfront walk"],
    rating: 4.6,
  },

  {
    type: "activity",
    title: "Boudhanath Kora Walk",
    description: "Traditional clockwise circuit around the stupa with cultural insight.",
    location: { name: "Boudhanath Stupa", address: "Boudha Circle, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7215, lng: 85.362 },
    pricePerUnit: 300,
    capacity: 25,
    amenities: ["Guided route", "Cultural notes", "Stupa access"],
    rating: 4.8,
  },
  {
    type: "activity",
    title: "Tibetan Monastery Visit",
    description: "Visit nearby monasteries and learn about Buddhist practice around Boudha.",
    location: { name: "Boudhanath Stupa", address: "Boudha Monastery Area, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7222, lng: 85.3618 },
    pricePerUnit: 800,
    capacity: 12,
    amenities: ["Guide", "Monastery access", "Rooftop stop"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Boudha Rooftop Sunset View",
    description: "Relaxed sunset session with tea and a rooftop view over the stupa.",
    location: { name: "Boudhanath Stupa", address: "Boudha Rooftop Area, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7218, lng: 85.3625 },
    pricePerUnit: 700,
    capacity: 10,
    amenities: ["Rooftop seat", "Tea option", "Stupa view"],
    rating: 4.6,
  },

  {
    type: "activity",
    title: "Durbar Square Walking Tour",
    description: "Guided heritage walk through the main monuments of Basantapur.",
    location: { name: "Kathmandu Durbar Square", address: "Basantapur, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7049, lng: 85.3075 },
    pricePerUnit: 1200,
    capacity: 15,
    amenities: ["Heritage guide", "Palace route", "Photo stops"],
    rating: 4.8,
  },
  {
    type: "activity",
    title: "Kumari Courtyard Visit",
    description: "Short stop focused on the living goddess tradition and old royal courtyards.",
    location: { name: "Kathmandu Durbar Square", address: "Basantapur Courtyard Area, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7052, lng: 85.3072 },
    pricePerUnit: 500,
    capacity: 20,
    amenities: ["Guide", "Heritage stop", "Courtyard access"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Old City Photo Walk",
    description: "Street-and-architecture photo walk from Durbar Square toward market lanes.",
    location: { name: "Kathmandu Durbar Square", address: "Durbar Square to Asan Route, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7055, lng: 85.308 },
    pricePerUnit: 1000,
    capacity: 10,
    amenities: ["Guide", "Walking route", "Photo support"],
    rating: 4.6,
  },

  {
    type: "activity",
    title: "Hanuman Dhoka Museum Entry",
    description: "Explore palace courtyards and museum halls within the historic complex.",
    location: { name: "Hanuman Dhoka Palace", address: "Hanuman Dhoka Complex, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7048, lng: 85.3076 },
    pricePerUnit: 800,
    capacity: 20,
    amenities: ["Museum entry", "Exhibit halls", "Palace route"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Malla History Tour",
    description: "Historical walkthrough focused on palace power and dynastic history.",
    location: { name: "Hanuman Dhoka Palace", address: "Hanuman Dhoka Palace, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7047, lng: 85.3078 },
    pricePerUnit: 1200,
    capacity: 12,
    amenities: ["Guide", "Storytelling", "Palace access"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Courtyard Heritage Visit",
    description: "Shorter heritage experience focused on palace spaces and architecture.",
    location: { name: "Hanuman Dhoka Palace", address: "Palace Courtyard Zone, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7049, lng: 85.3074 },
    pricePerUnit: 600,
    capacity: 15,
    amenities: ["Guide", "Architecture notes", "Short route"],
    rating: 4.4,
  },

  {
    type: "activity",
    title: "Garden Entry Visit",
    description: "Quiet visit through one of central Kathmandu's most restful public heritage gardens.",
    location: { name: "Garden of Dreams", address: "Kaiser Mahal, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7134, lng: 85.3156 },
    pricePerUnit: 400,
    capacity: 30,
    amenities: ["Garden access", "Seating", "Restrooms"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Garden Tea Break",
    description: "Relaxed tea and cafe session inside the garden setting.",
    location: { name: "Garden of Dreams", address: "Garden Cafe Area, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7131, lng: 85.3158 },
    pricePerUnit: 800,
    capacity: 8,
    amenities: ["Cafe seating", "Garden table", "Calm setting"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Architectural Garden Walk",
    description: "Short guided tour of the garden design and restoration story.",
    location: { name: "Garden of Dreams", address: "Garden of Dreams, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7136, lng: 85.3154 },
    pricePerUnit: 700,
    capacity: 12,
    amenities: ["Guide", "Heritage notes", "Photo spots"],
    rating: 4.3,
  },

  {
    type: "activity",
    title: "Narayanhiti Museum Visit",
    description: "Explore the former royal palace rooms and modern political exhibits.",
    location: { name: "Narayanhiti Palace Museum", address: "Durbar Marg, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7173, lng: 85.3217 },
    pricePerUnit: 1000,
    capacity: 20,
    amenities: ["Museum entry", "Exhibit halls", "Palace route"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Royal History Tour",
    description: "Guided interpretation of Nepal's royal history through the museum complex.",
    location: { name: "Narayanhiti Palace Museum", address: "Narayanhiti Complex, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7171, lng: 85.3215 },
    pricePerUnit: 1500,
    capacity: 10,
    amenities: ["Guide", "Timeline briefing", "Museum access"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Museum Architecture Walk",
    description: "Short route centered on the grounds, exterior details, and political symbolism.",
    location: { name: "Narayanhiti Palace Museum", address: "Museum Grounds, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7175, lng: 85.3219 },
    pricePerUnit: 800,
    capacity: 12,
    amenities: ["Guide", "Exterior route", "Photo stop"],
    rating: 4.3,
  },

  {
    type: "activity",
    title: "Budhanilkantha Shrine Visit",
    description: "Visit the famous reclining Vishnu image in the sacred pond.",
    location: { name: "Budhanilkantha Temple", address: "Budhanilkantha, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7807, lng: 85.3672 },
    pricePerUnit: 300,
    capacity: 25,
    amenities: ["Temple access", "Prayer area", "Local shops nearby"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Temple and Village Walk",
    description: "Short cultural walk around the Budhanilkantha area after the shrine visit.",
    location: { name: "Budhanilkantha Temple", address: "Budhanilkantha Area, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7802, lng: 85.3675 },
    pricePerUnit: 800,
    capacity: 12,
    amenities: ["Guide", "Local route", "Cultural stop"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Pilgrimage Culture Tour",
    description: "Guided overview of temple symbolism and local pilgrimage practices.",
    location: { name: "Budhanilkantha Temple", address: "Temple Zone, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7809, lng: 85.3671 },
    pricePerUnit: 1000,
    capacity: 10,
    amenities: ["Guide", "Ritual explanation", "Temple stop"],
    rating: 4.5,
  },

  {
    type: "activity",
    title: "Chandragiri Cable Car Ride",
    description: "Ride the cable car for a fast hill ascent and valley views.",
    location: { name: "Chandragiri Hills", address: "Thankot Cable Car Base, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.6741, lng: 85.2052 },
    pricePerUnit: 2500,
    capacity: 6,
    amenities: ["Cable car ticket", "Viewpoint access", "Transport hub"],
    rating: 4.8,
  },
  {
    type: "activity",
    title: "Hilltop View Session",
    description: "Scenic viewpoint stop from the Chandragiri summit station.",
    location: { name: "Chandragiri Hills", address: "Chandragiri Top Station, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.6738, lng: 85.2057 },
    pricePerUnit: 500,
    capacity: 20,
    amenities: ["View deck", "Rest area", "Photo spots"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Bhaleshwor Temple Visit",
    description: "Temple stop added to the Chandragiri hill experience.",
    location: { name: "Chandragiri Hills", address: "Bhaleshwor Mahadev Area, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.6742, lng: 85.2059 },
    pricePerUnit: 600,
    capacity: 20,
    amenities: ["Temple access", "Short walk", "Viewpoint route"],
    rating: 4.5,
  },

  {
    type: "activity",
    title: "Shivapuri Day Hike",
    description: "A full-day forest hike from the Budhanilkantha side of the park.",
    location: { name: "Shivapuri Nagarjun National Park", address: "Budhanilkantha Gate, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.8075, lng: 85.3659 },
    pricePerUnit: 1800,
    capacity: 12,
    amenities: ["Guide", "Trail route", "Entry support"],
    rating: 4.8,
  },
  {
    type: "activity",
    title: "Birdwatching Forest Walk",
    description: "Nature-focused walk for birdlife and cooler forest surroundings.",
    location: { name: "Shivapuri Nagarjun National Park", address: "Shivapuri Forest Trail, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.8101, lng: 85.3724 },
    pricePerUnit: 1200,
    capacity: 8,
    amenities: ["Guide", "Binocular support", "Forest trail"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Nature Photography Trek",
    description: "Soft-adventure walk designed for landscape and forest photography.",
    location: { name: "Shivapuri Nagarjun National Park", address: "Park Trailhead, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.8087, lng: 85.3704 },
    pricePerUnit: 1600,
    capacity: 10,
    amenities: ["Guide", "Scenic route", "Rest stops"],
    rating: 4.6,
  },

  {
    type: "activity",
    title: "Kopan Monastery Visit",
    description: "Quiet cultural stop with monastery grounds and spiritual atmosphere.",
    location: { name: "Kopan Monastery", address: "Kopan Hill, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7425, lng: 85.3679 },
    pricePerUnit: 500,
    capacity: 20,
    amenities: ["Monastery access", "Garden areas", "Calm setting"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Meditation Intro Session",
    description: "Beginner-friendly short meditation experience in a peaceful setting.",
    location: { name: "Kopan Monastery", address: "Kopan Monastery Area, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7428, lng: 85.3676 },
    pricePerUnit: 1200,
    capacity: 15,
    amenities: ["Guided session", "Calm space", "Seating"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Hilltop Peace Walk",
    description: "Short reflective walk around the monastery's hillside surroundings.",
    location: { name: "Kopan Monastery", address: "Kopan Surroundings, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7431, lng: 85.3682 },
    pricePerUnit: 700,
    capacity: 10,
    amenities: ["Guide", "Walking path", "Viewpoint stop"],
    rating: 4.4,
  },

  {
    type: "activity",
    title: "Asan Food Walk",
    description: "Old-market tasting route through spice, snack, and street-food stops.",
    location: { name: "Asan Bazaar", address: "Asan, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7076, lng: 85.3126 },
    pricePerUnit: 1200,
    capacity: 10,
    amenities: ["Food guide", "Tasting stops", "Walking route"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Local Shopping Tour",
    description: "Traditional market shopping route through Asan and nearby lanes.",
    location: { name: "Asan Bazaar", address: "Asan to Indra Chowk, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7079, lng: 85.3121 },
    pricePerUnit: 900,
    capacity: 12,
    amenities: ["Guide", "Market route", "Bargaining help"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Newar Heritage Street Walk",
    description: "Cultural street walk connecting market life with historic urban form.",
    location: { name: "Asan Bazaar", address: "Old Market Lanes, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7073, lng: 85.3131 },
    pricePerUnit: 1000,
    capacity: 12,
    amenities: ["Guide", "Heritage commentary", "Market stops"],
    rating: 4.5,
  },

  {
    type: "hotel",
    title: "Hotel Shanker",
    description: "Heritage-style central stay with easy access to museums, gardens, and palace areas.",
    location: { name: "Garden of Dreams", address: "Lazimpat, near Garden of Dreams access, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7213, lng: 85.3185 },
    pricePerUnit: 9500,
    capacity: 2,
    amenities: ["Pool", "Restaurant", "Garden", "Wi-Fi"],
    rating: 4.5,
  },
  {
    type: "hotel",
    title: "Kathmandu Marriott Hotel",
    description: "Premium modern hotel convenient for palace, museum, and embassy-zone travel.",
    location: { name: "Narayanhiti Palace Museum", address: "Naxal, near Narayanhiti area, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.716, lng: 85.3275 },
    pricePerUnit: 18000,
    capacity: 2,
    amenities: ["Pool", "Gym", "Restaurant", "Airport transfer"],
    rating: 4.7,
  },
  {
    type: "hotel",
    title: "Aloft Kathmandu Thamel",
    description: "Stylish hotel close to Kathmandu's tourism core and old-city access.",
    location: { name: "Kathmandu Durbar Square", address: "Thamel edge, convenient for Durbar Square visits, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.713, lng: 85.3117 },
    pricePerUnit: 14000,
    capacity: 2,
    amenities: ["Rooftop bar", "Gym", "Wi-Fi", "Restaurant"],
    rating: 4.6,
  },
  {
    type: "hotel",
    title: "Hotel Yak and Yeti",
    description: "Classic upscale city hotel near major cultural and business areas.",
    location: { name: "Garden of Dreams", address: "Durbar Marg, near central heritage route, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7119, lng: 85.3205 },
    pricePerUnit: 16000,
    capacity: 2,
    amenities: ["Garden", "Pool", "Restaurants", "Event spaces"],
    rating: 4.5,
  },
  {
    type: "hotel",
    title: "Fairfield by Marriott Kathmandu",
    description: "Reliable central stay with convenient access to Thamel and nearby heritage sites.",
    location: { name: "Asan Bazaar", address: "Thamel, close to Asan and old market routes, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7124, lng: 85.3128 },
    pricePerUnit: 11000,
    capacity: 2,
    amenities: ["Breakfast", "Wi-Fi", "Gym", "Business support"],
    rating: 4.4,
  },

  {
    type: "cafe",
    title: "Himalayan Java Durbar Marg",
    description: "Popular coffee stop for tourists near the central city heritage route.",
    location: { name: "Garden of Dreams", address: "Durbar Marg, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7138, lng: 85.3179 },
    pricePerUnit: 500,
    capacity: 26,
    amenities: ["Coffee", "Bakery", "Work-friendly seating"],
    rating: 4.4,
  },
  {
    type: "cafe",
    title: "Pumpernickel Bakery",
    description: "Traveler-friendly bakery cafe known for breakfast, bread, and coffee.",
    location: { name: "Asan Bazaar", address: "Thamel, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7151, lng: 85.312 },
    pricePerUnit: 650,
    capacity: 20,
    amenities: ["Bakery", "Breakfast", "Coffee"],
    rating: 4.5,
  },
  {
    type: "cafe",
    title: "Calm Restro and Cafe",
    description: "Rooftop-style cafe near Boudha with a relaxed stupa-facing atmosphere.",
    location: { name: "Boudhanath Stupa", address: "Boudha, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7219, lng: 85.3629 },
    pricePerUnit: 700,
    capacity: 24,
    amenities: ["Rooftop view", "Coffee", "Tea", "Casual dining"],
    rating: 4.4,
  },

  {
    type: "restaurant",
    title: "Krishnarpan at Dwarikas",
    description: "Fine-dining Nepali tasting experience with refined traditional presentation.",
    location: { name: "Pashupatinath Temple", address: "Battisputali, near Pashupatinath route, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7057, lng: 85.3456 },
    pricePerUnit: 3500,
    capacity: 28,
    amenities: ["Fine dining", "Traditional menu", "Reservation-friendly"],
    rating: 4.8,
  },
  {
    type: "restaurant",
    title: "OR2K Kathmandu",
    description: "A relaxed vegetarian-friendly restaurant popular with travelers in the tourism core.",
    location: { name: "Asan Bazaar", address: "Thamel, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7139, lng: 85.3114 },
    pricePerUnit: 1200,
    capacity: 32,
    amenities: ["Vegetarian options", "Indoor seating", "Travel-friendly"],
    rating: 4.5,
  },
  {
    type: "restaurant",
    title: "Bhojan Griha",
    description: "Traditional Nepali dining venue with cultural atmosphere in a heritage-style setting.",
    location: { name: "Pashupatinath Temple", address: "Dillibazar, convenient for Pashupatinath visitors, Kathmandu", district: "Kathmandu", province: "Bagmati", lat: 27.7092, lng: 85.3279 },
    pricePerUnit: 2200,
    capacity: 36,
    amenities: ["Cultural dining", "Local cuisine", "Indoor seating"],
    rating: 4.6,
  },
];

const nearbyRecommendations = [
  { name: "Patan Durbar Square", distanceKm: 6, mainActivity: "Heritage walking tour" },
  { name: "Bhaktapur Durbar Square", distanceKm: 15, mainActivity: "Cultural sightseeing and old-city walk" },
  { name: "Changu Narayan Temple", distanceKm: 14, mainActivity: "Temple heritage tour" },
  { name: "Nagarkot", distanceKm: 28, mainActivity: "Sunrise viewpoint and short hiking" },
  { name: "Dhulikhel", distanceKm: 30, mainActivity: "Hill walk and Himalayan viewpoint" },
];

module.exports = {
  locationSeeds,
  listingSeeds,
  nearbyRecommendations,
};
