const tripPackageSeeds = [
  {
    title: "Kathmandu Heritage Discovery",
    slug: "kathmandu-heritage-discovery",
    shortDescription:
      "A classic Kathmandu culture package covering the old royal square, market lanes, major stupas, and sacred river heritage.",
    description:
      "Ideal for first-time visitors who want a structured introduction to Kathmandu's living heritage. This package combines Kathmandu Durbar Square, Asan market culture, Swayambhunath, Pashupatinath, and Boudhanath into one compact and polished city experience.",
    location: "Kathmandu",
    region: "Bagmati Province",
    pickupCity: "Tribhuvan International Airport",
    dropoffCity: "Tribhuvan International Airport",
    startDate: "2026-09-18",
    endDate: "2026-09-19",
    basePrice: 12500,
    discountPrice: 11400,
    rating: 4.7,
    currency: "NPR",
    capacity: 12,
    minGuests: 1,
    maxGuests: 12,
    coverImage: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1400&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1501556424050-d4816356b73e?auto=format&fit=crop&w=1200&q=80",
    ],
    included: [
      "1 night hotel stay in central Kathmandu",
      "Airport pickup and drop",
      "Breakfast",
      "Kathmandu Durbar Square heritage walk",
      "Asan old-market cultural walk",
      "Swayambhunath visit",
      "Pashupatinath orientation tour",
      "Boudhanath stupa circuit",
    ],
    excluded: ["Lunch and dinner", "Personal temple offerings", "Travel insurance"],
    highlights: ["Kathmandu Durbar Square", "Asan Bazaar", "Swayambhunath", "Pashupatinath and Boudhanath"],
    bestSeason: "September to May",
    difficulty: "Easy",
    tripType: "Cultural Heritage",
    cancellationPolicy:
      "Free cancellation up to 5 days before travel. 25% charge within 48 hours of the trip.",
    paymentPolicy:
      "25% advance payment required to confirm. Remaining balance payable before the Day 2 city circuit.",
    faqs: [
      {
        question: "Is this package suitable for solo travelers?",
        answer: "Yes. Solo travelers, couples, and small groups can all book this package comfortably.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Arrival and old-city heritage walk",
        summary:
          "Arrive in Kathmandu, check in, explore Kathmandu Durbar Square, and continue through Asan and surrounding old-city lanes.",
        hotelTitle: "Hotel Shanker",
        meals: ["Welcome drink"],
        transport: "Private airport and city transfer",
        altitude: "1,400 m",
        notes: "Best done in comfortable walking shoes due to uneven heritage paths.",
        image: "",
        activities: [
          { listingTitle: "Durbar Square Walking Tour", notes: "Guided heritage orientation." },
          { listingTitle: "Asan Food Walk", notes: "Evening market exploration with local context." },
        ],
      },
      {
        dayNumber: 2,
        title: "Temple and stupa circuit",
        summary:
          "Visit Swayambhunath, Pashupatinath, and Boudhanath before the airport transfer.",
        hotelTitle: "Hotel Shanker",
        meals: ["Breakfast"],
        transport: "Private heritage vehicle",
        altitude: "1,400 m",
        notes: "Modest clothing is recommended for temple areas.",
        image: "",
        activities: [
          { listingTitle: "Swayambhunath Heritage Walk", notes: "Morning hilltop visit." },
          { listingTitle: "Pashupatinath Darshan Circuit", notes: "Sacred heritage zone walkthrough." },
          { listingTitle: "Boudhanath Kora Walk", notes: "Final stupa visit before departure." },
        ],
      },
    ],
    addOnTitles: ["Bagmati Aarati Viewing", "OR2K Kathmandu", "Himalayan Java Durbar Marg"],
    isFeatured: true,
    isActive: true,
  },
  {
    title: "Kathmandu Spiritual Temple Trail",
    slug: "kathmandu-spiritual-temple-trail",
    shortDescription:
      "A spiritually focused Kathmandu package built around sacred temples, monasteries, rituals, and quiet reflection spaces.",
    description:
      "This package is designed for travelers who want a more contemplative Kathmandu journey. It combines major Hindu and Buddhist sacred sites with monastery time, ritual observation, and gentler pacing.",
    location: "Kathmandu",
    region: "Bagmati Province",
    pickupCity: "Tribhuvan International Airport",
    dropoffCity: "Tribhuvan International Airport",
    startDate: "2026-10-09",
    endDate: "2026-10-11",
    basePrice: 16800,
    discountPrice: 15400,
    rating: 4.8,
    currency: "NPR",
    capacity: 10,
    minGuests: 1,
    maxGuests: 10,
    coverImage: "https://images.unsplash.com/photo-1493558103817-58b2924bce98?auto=format&fit=crop&w=1400&q=80",
    galleryImages: [],
    included: [
      "2 nights hotel stay",
      "Airport transfers",
      "Daily breakfast",
      "Pashupatinath heritage tour",
      "Bagmati aarati viewing",
      "Boudhanath kora and monastery visit",
      "Kopan Monastery session",
      "Budhanilkantha visit",
    ],
    excluded: ["Lunch and dinner", "Personal donations", "Meditation course fees beyond package inclusions"],
    highlights: ["Pashupatinath rituals", "Boudhanath kora", "Kopan Monastery", "Budhanilkantha shrine"],
    bestSeason: "October to April",
    difficulty: "Easy",
    tripType: "Spiritual and Temple Tour",
    cancellationPolicy: "Free cancellation up to 7 days before departure. 30% charge within 72 hours.",
    paymentPolicy: "30% advance payment required. Remaining balance due at hotel check-in.",
    faqs: [
      {
        question: "Can non-Hindu travelers join the Pashupatinath package?",
        answer: "Yes. The outer complex, heritage routes, and riverfront ritual areas are still meaningful and accessible.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Arrival and evening sacred Kathmandu",
        summary:
          "Check in and head to Pashupatinath for a cultural orientation before joining the Bagmati aarati atmosphere in the evening.",
        hotelTitle: "Hotel Yak and Yeti",
        meals: ["Welcome drink"],
        transport: "Private city transfer",
        altitude: "1,400 m",
        notes: "Evening timing depends on ritual schedule.",
        image: "",
        activities: [
          { listingTitle: "Hindu Heritage Tour", notes: "Introductory temple and sacred geography tour." },
          { listingTitle: "Bagmati Aarati Viewing", notes: "Evening river ritual experience." },
        ],
      },
      {
        dayNumber: 2,
        title: "Boudha and monastery reflection",
        summary:
          "Spend the day at Boudhanath and Kopan, with a balance of spiritual interpretation and quiet time.",
        hotelTitle: "Hotel Yak and Yeti",
        meals: ["Breakfast"],
        transport: "Private spiritual circuit transfer",
        altitude: "1,400 m",
        notes: "Ideal for slow-paced travelers seeking a reflective day.",
        image: "",
        activities: [
          { listingTitle: "Boudhanath Kora Walk", notes: "Morning stupa circuit." },
          { listingTitle: "Tibetan Monastery Visit", notes: "Monastic culture and architecture stop." },
          { listingTitle: "Meditation Intro Session", notes: "Light contemplative session at Kopan." },
        ],
      },
      {
        dayNumber: 3,
        title: "Budhanilkantha and departure",
        summary:
          "Visit the Budhanilkantha shrine in the morning, return for breakfast, and transfer to the airport.",
        hotelTitle: "Hotel Yak and Yeti",
        meals: ["Breakfast"],
        transport: "Private airport transfer",
        altitude: "1,400 m",
        notes: "A calm final morning with less walking.",
        image: "",
        activities: [{ listingTitle: "Budhanilkantha Shrine Visit", notes: "Sacred Vishnu shrine visit." }],
      },
    ],
    addOnTitles: ["Hilltop Peace Walk", "Calm Restro and Cafe", "Boudha Rooftop Sunset View"],
    isFeatured: true,
    isActive: true,
  },
  {
    title: "Kathmandu Art Culture and Heritage Walk",
    slug: "kathmandu-art-culture-and-heritage-walk",
    shortDescription:
      "A compact package focused on courtyards, museums, garden architecture, street culture, and artisan-friendly heritage spaces.",
    description:
      "A strong fit for design, art, and culture lovers who want to explore Kathmandu through architecture, museums, palace compounds, gardens, and old-city textures.",
    location: "Kathmandu",
    region: "Bagmati Province",
    pickupCity: "Tribhuvan International Airport",
    dropoffCity: "Tribhuvan International Airport",
    startDate: "2026-11-06",
    endDate: "2026-11-07",
    basePrice: 11200,
    discountPrice: 10200,
    rating: 4.6,
    currency: "NPR",
    capacity: 15,
    minGuests: 2,
    maxGuests: 15,
    coverImage: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1400&q=80",
    galleryImages: [],
    included: [
      "1 night hotel stay",
      "Breakfast",
      "Airport pickup and drop",
      "Kathmandu Durbar Square walk",
      "Hanuman Dhoka museum entry",
      "Garden of Dreams visit",
      "Narayanhiti Palace Museum visit",
    ],
    excluded: ["Lunch and dinner", "Personal shopping", "Guide overtime beyond listed route"],
    highlights: ["Royal courtyards", "Museum interiors", "Garden architecture", "Old-city photography"],
    bestSeason: "September to May",
    difficulty: "Easy",
    tripType: "Art and Heritage Walk",
    cancellationPolicy: "Free cancellation up to 5 days before travel. 20% charge within 48 hours.",
    paymentPolicy: "25% advance payment required for confirmation.",
    faqs: [
      {
        question: "Is this suitable for photographers and architecture students?",
        answer: "Yes. This package is especially good for visual reference, cultural details, and slower museum visits.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Durbar Square and palace culture",
        summary:
          "Arrive in Kathmandu, check in, walk through Durbar Square, and continue to Hanuman Dhoka museum spaces.",
        hotelTitle: "Aloft Kathmandu Thamel",
        meals: ["Welcome drink"],
        transport: "Private airport transfer",
        altitude: "1,400 m",
        notes: "Good natural light for photos in the afternoon courtyard zones.",
        image: "",
        activities: [
          { listingTitle: "Durbar Square Walking Tour", notes: "Historic square overview." },
          { listingTitle: "Hanuman Dhoka Museum Entry", notes: "Museum and palace interiors." },
          { listingTitle: "Old City Photo Walk", notes: "Street texture and heritage photography route." },
        ],
      },
      {
        dayNumber: 2,
        title: "Garden architecture and museum route",
        summary:
          "Visit the Garden of Dreams and Narayanhiti Palace Museum before airport drop.",
        hotelTitle: "Aloft Kathmandu Thamel",
        meals: ["Breakfast"],
        transport: "Private city transfer",
        altitude: "1,400 m",
        notes: "A calm final day with balanced indoor and outdoor stops.",
        image: "",
        activities: [
          { listingTitle: "Architectural Garden Walk", notes: "Garden design and quiet city retreat." },
          { listingTitle: "Royal History Tour", notes: "Palace-state history and interiors." },
        ],
      },
    ],
    addOnTitles: ["Pumpernickel Bakery", "Himalayan Java Durbar Marg", "Local Shopping Tour"],
    isFeatured: false,
    isActive: true,
  },
  {
    title: "Kathmandu Royal Squares and Rituals",
    slug: "kathmandu-royal-squares-and-rituals",
    shortDescription:
      "A deeper Kathmandu package blending royal history, old-city lanes, temple heritage, evening ritual culture, and premium city comfort.",
    description:
      "This itinerary is made for travelers who want more depth than a basic city tour. It combines royal heritage, old city movement, temple ritual spaces, and select premium cultural stops across three days.",
    location: "Kathmandu",
    region: "Bagmati Province",
    pickupCity: "Tribhuvan International Airport",
    dropoffCity: "Tribhuvan International Airport",
    startDate: "2026-10-23",
    endDate: "2026-10-25",
    basePrice: 18500,
    discountPrice: 17100,
    rating: 4.8,
    currency: "NPR",
    capacity: 12,
    minGuests: 2,
    maxGuests: 12,
    coverImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=80",
    galleryImages: [],
    included: [
      "2 nights premium hotel stay",
      "Daily breakfast",
      "Airport transfers",
      "Kathmandu Durbar Square and palace circuit",
      "Old-city market walk",
      "Pashupatinath and evening aarati",
      "Boudhanath sunset rooftop stop",
    ],
    excluded: ["Lunch and dinner", "Private photographer", "Personal offerings and donations"],
    highlights: ["Royal history", "Old-city market life", "Bagmati aarati", "Boudha sunset"],
    bestSeason: "October to April",
    difficulty: "Easy",
    tripType: "Royal Heritage and Ritual",
    cancellationPolicy: "Free cancellation up to 7 days before departure. 30% charge within 72 hours.",
    paymentPolicy: "30% advance required to confirm premium hotel and transport scheduling.",
    faqs: [
      {
        question: "Is this package very crowded or rushed?",
        answer: "No. It is paced more comfortably than a same-day city circuit and includes slower cultural stops.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Arrival and royal old-city circuit",
        summary:
          "Check in and spend the afternoon in Kathmandu Durbar Square, Hanuman Dhoka, and adjoining market lanes.",
        hotelTitle: "Kathmandu Marriott Hotel",
        meals: ["Welcome drink"],
        transport: "Private airport transfer",
        altitude: "1,400 m",
        notes: "A balanced arrival day with moderate walking.",
        image: "",
        activities: [
          { listingTitle: "Durbar Square Walking Tour", notes: "Royal square overview." },
          { listingTitle: "Courtyard Heritage Visit", notes: "Focused palace and courtyard stop." },
          { listingTitle: "Newar Heritage Street Walk", notes: "Local lane culture and architecture." },
        ],
      },
      {
        dayNumber: 2,
        title: "Sacred river and evening ritual culture",
        summary:
          "Visit Pashupatinath in depth and stay into the evening for Bagmati aarati.",
        hotelTitle: "Kathmandu Marriott Hotel",
        meals: ["Breakfast"],
        transport: "Private city vehicle",
        altitude: "1,400 m",
        notes: "Modest attire is encouraged.",
        image: "",
        activities: [
          { listingTitle: "Pashupatinath Darshan Circuit", notes: "Temple complex route." },
          { listingTitle: "Bagmati Aarati Viewing", notes: "Evening ritual viewing." },
        ],
      },
      {
        dayNumber: 3,
        title: "Boudha and departure",
        summary:
          "Wrap the trip with Boudhanath and a rooftop valley view before departure.",
        hotelTitle: "Kathmandu Marriott Hotel",
        meals: ["Breakfast"],
        transport: "Private departure transfer",
        altitude: "1,400 m",
        notes: "Ideal last-day stop for a calmer farewell to Kathmandu.",
        image: "",
        activities: [
          { listingTitle: "Boudhanath Kora Walk", notes: "Morning stupa circuit." },
          { listingTitle: "Boudha Rooftop Sunset View", notes: "Can be switched to skyline brunch timing if needed." },
        ],
      },
    ],
    addOnTitles: ["Krishnarpan at Dwarikas", "Garden Tea Break", "Museum Architecture Walk"],
    isFeatured: true,
    isActive: true,
  },
  {
    title: "Kathmandu Family Cultural Escape",
    slug: "kathmandu-family-cultural-escape",
    shortDescription:
      "A family-friendly Kathmandu cultural package with easy sightseeing, open spaces, and gentle heritage learning.",
    description:
      "Designed for families and mixed-age groups, this package keeps the pace soft and practical while still delivering a strong Kathmandu cultural experience with gardens, viewpoints, and manageable walking distances.",
    location: "Kathmandu",
    region: "Bagmati Province",
    pickupCity: "Tribhuvan International Airport",
    dropoffCity: "Tribhuvan International Airport",
    startDate: "2026-12-04",
    endDate: "2026-12-05",
    basePrice: 10800,
    discountPrice: 9800,
    rating: 4.5,
    currency: "NPR",
    capacity: 14,
    minGuests: 2,
    maxGuests: 14,
    coverImage: "https://images.unsplash.com/photo-1501556424050-d4816356b73e?auto=format&fit=crop&w=1400&q=80",
    galleryImages: [],
    included: [
      "1 night family-friendly hotel stay",
      "Breakfast",
      "Airport pickup and drop",
      "Garden of Dreams visit",
      "Swayambhunath visit",
      "Chandragiri cable car ride",
      "Basic cultural guide support",
    ],
    excluded: ["Lunch and dinner", "Personal shopping", "Adventure activities beyond itinerary"],
    highlights: ["Family pace", "Open garden stop", "Hill cable car ride", "Cultural sightseeing"],
    bestSeason: "September to May",
    difficulty: "Easy",
    tripType: "Family Cultural Tour",
    cancellationPolicy: "Free cancellation up to 5 days before departure. 20% charge within 48 hours.",
    paymentPolicy: "25% advance required. Full balance due at hotel check-in.",
    faqs: [
      {
        question: "Is this suitable for children and seniors?",
        answer: "Yes. The package is lighter on walking and includes easier scenic and cultural stops.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Arrival and relaxed Kathmandu",
        summary:
          "Arrive in Kathmandu, check in, and spend the afternoon at the Garden of Dreams before a relaxed evening.",
        hotelTitle: "Fairfield by Marriott Kathmandu",
        meals: ["Welcome drink"],
        transport: "Private family transfer",
        altitude: "1,400 m",
        notes: "Good first-day choice for travelers adjusting after arrival.",
        image: "",
        activities: [
          { listingTitle: "Garden Entry Visit", notes: "Relaxed family-friendly city stop." },
          { listingTitle: "Garden Tea Break", notes: "Optional quiet refreshment stop." },
        ],
      },
      {
        dayNumber: 2,
        title: "Viewpoint and family heritage route",
        summary:
          "Visit Swayambhunath and then take the Chandragiri cable car before departure.",
        hotelTitle: "Fairfield by Marriott Kathmandu",
        meals: ["Breakfast"],
        transport: "Private family vehicle",
        altitude: "1,400 m to 2,551 m",
        notes: "A scenic and low-strain final day.",
        image: "",
        activities: [
          { listingTitle: "Swayambhunath Heritage Walk", notes: "Morning heritage stop." },
          { listingTitle: "Chandragiri Cable Car Ride", notes: "Family-friendly valley viewpoint excursion." },
        ],
      },
    ],
    addOnTitles: ["Bhojan Griha", "Local Shopping Tour", "Hilltop View Session"],
    isFeatured: false,
    isActive: true,
  },
];

module.exports = {
  tripPackageSeeds,
};
