const tripPackageSeeds = [
  {
    title: "Lumbini Sacred Birthplace Experience",
    slug: "lumbini-sacred-birthplace-experience",
    shortDescription:
      "A focused 2-day Lumbini pilgrimage package covering Maya Devi Temple, Sacred Garden, Ashoka Pillar, monasteries, and the World Peace Pagoda.",
    description:
      "Designed for first-time Lumbini visitors who want a calm and meaningful introduction to Buddha's birthplace. This package balances sacred history, slow walking, monastery architecture, and peaceful reflection time without rushing the core pilgrimage area.",
    location: "Lumbini",
    region: "Lumbini Province",
    pickupCity: "Gautam Buddha International Airport / Bhairahawa",
    dropoffCity: "Gautam Buddha International Airport / Bhairahawa",
    startDate: "2026-09-17",
    endDate: "2026-09-18",
    basePrice: 11800,
    discountPrice: 10800,
    rating: 4.8,
    currency: "NPR",
    capacity: 12,
    minGuests: 1,
    maxGuests: 12,
    coverImage: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1400&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    ],
    videoUrl: "",
    included: [
      "1 night hotel stay near Lumbini",
      "Airport or Bhairahawa pickup and drop",
      "Breakfast",
      "Maya Devi Temple sacred walk",
      "Ashoka Pillar heritage briefing",
      "Sacred Garden mindful walk",
      "World Peace Pagoda visit",
      "Local coordinator support",
    ],
    excluded: ["Lunch and dinner", "Personal offerings", "Travel insurance", "Extra monastery donations"],
    highlights: ["Maya Devi Temple", "Ashoka Pillar", "Sacred Garden", "World Peace Pagoda"],
    bestSeason: "October to March",
    difficulty: "Easy",
    tripType: "Spiritual Pilgrimage",
    cancellationPolicy: "Free cancellation up to 5 days before travel. 20% charge within 48 hours.",
    paymentPolicy: "25% advance payment required to confirm hotel and transfer.",
    faqs: [
      {
        question: "Is this suitable for elderly pilgrims?",
        answer: "Yes. The route is mostly gentle, and private transfer support can reduce walking where needed.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Arrival and sacred birthplace walk",
        summary:
          "Arrive in Lumbini, check in, then visit Maya Devi Temple, Ashoka Pillar, and the Sacred Garden at a gentle pace.",
        hotelTitle: "Buddha Maya Garden Hotel",
        meals: ["Welcome tea"],
        transport: "Private airport or Bhairahawa transfer",
        altitude: "150 m",
        notes: "Modest clothing and quiet behavior are recommended inside sacred areas.",
        image: "",
        activities: [
          { listingTitle: "Maya Devi Temple Sacred Walk", notes: "Core birthplace visit." },
          { listingTitle: "Ashoka Pillar Heritage Briefing", notes: "Historical context beside the pillar." },
          { listingTitle: "Sacred Garden Mindful Walk", notes: "Slow garden route and reflection time." },
        ],
      },
      {
        dayNumber: 2,
        title: "Peace pagoda, monastic zone, and departure",
        summary:
          "Explore the monastery side of Lumbini, visit the World Peace Pagoda, and transfer for departure.",
        hotelTitle: "Buddha Maya Garden Hotel",
        meals: ["Breakfast"],
        transport: "Private local transfer",
        altitude: "150 m",
        notes: "A morning cycle tour can be added if guests prefer an active route.",
        image: "",
        activities: [
          { listingTitle: "World Peace Pagoda Sunset Visit", notes: "Can be done in morning if departure is early." },
          { listingTitle: "Royal Thai Monastery Architecture Stop", notes: "Selected monastery visit." },
        ],
      },
    ],
    addOnTitles: ["Lumbini Monastic Zone Cycling Tour", "Maya Devi Garden Cafe", "Three Vision Restaurant Lumbini"],
    isFeatured: true,
    isActive: true,
  },
  {
    title: "Lumbini Monastery and Meditation Retreat",
    slug: "lumbini-monastery-meditation-retreat",
    shortDescription:
      "A slow 3-day Lumbini retreat focused on monastery architecture, mindful walking, museum learning, and quiet reflection.",
    description:
      "This package is designed for travelers seeking a softer spiritual pace. It combines the Sacred Garden with the eastern and western monastic zones, museum learning, cycling, tea breaks, and time for personal reflection.",
    location: "Lumbini",
    region: "Lumbini Province",
    pickupCity: "Gautam Buddha International Airport / Bhairahawa",
    dropoffCity: "Gautam Buddha International Airport / Bhairahawa",
    startDate: "2026-10-08",
    endDate: "2026-10-10",
    basePrice: 17500,
    discountPrice: 16200,
    rating: 4.7,
    currency: "NPR",
    capacity: 10,
    minGuests: 1,
    maxGuests: 10,
    coverImage: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1400&q=80",
    galleryImages: [],
    videoUrl: "",
    included: [
      "2 nights quiet hotel stay",
      "Daily breakfast",
      "Airport or Bhairahawa transfers",
      "Monastic zone cycling tour",
      "Museum learning tour",
      "Selected monastery visits",
      "Sacred Garden mindful walk",
    ],
    excluded: ["Lunch and dinner", "Formal meditation course fees", "Personal donations", "Travel insurance"],
    highlights: ["Monastic Zone", "Meditative walking", "Museum learning", "Thai and German monastery stops"],
    bestSeason: "November to February",
    difficulty: "Easy",
    tripType: "Mindfulness and Monastery Tour",
    cancellationPolicy: "Free cancellation up to 7 days before travel. 25% charge within 72 hours.",
    paymentPolicy: "30% advance payment required. Remaining balance due at hotel check-in.",
    faqs: [
      {
        question: "Is this a formal meditation course?",
        answer: "No. It is a travel retreat with quiet reflection spaces and optional meditation-friendly pacing.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Arrival and mindful sacred garden",
        summary:
          "Check in, settle into the quiet pace of Lumbini, and take a guided mindful walk through the Sacred Garden.",
        hotelTitle: "Lumbini Hokke Hotel",
        meals: ["Welcome tea"],
        transport: "Private transfer",
        altitude: "150 m",
        notes: "This day is intentionally light and reflective.",
        image: "",
        activities: [{ listingTitle: "Sacred Garden Mindful Walk", notes: "Gentle first-day route." }],
      },
      {
        dayNumber: 2,
        title: "Monastery cycling and architecture",
        summary:
          "Cycle through the monastic zone, stopping at the Royal Thai, German, and Myanmar monastery areas.",
        hotelTitle: "Lumbini Hokke Hotel",
        meals: ["Breakfast"],
        transport: "Bicycle and support vehicle",
        altitude: "150 m",
        notes: "Sunhat and water bottle are recommended.",
        image: "",
        activities: [
          { listingTitle: "Lumbini Monastic Zone Cycling Tour", notes: "Core monastery route." },
          { listingTitle: "Royal Thai Monastery Architecture Stop", notes: "Eastern monastic architecture." },
          { listingTitle: "German Monastery Art and Garden Walk", notes: "Western monastic zone art stop." },
          { listingTitle: "Myanmar Golden Temple Visit", notes: "Golden temple visit." },
        ],
      },
      {
        dayNumber: 3,
        title: "Museum learning and departure",
        summary:
          "Visit Lumbini Museum for context, enjoy a final tea break, and transfer for departure.",
        hotelTitle: "Lumbini Hokke Hotel",
        meals: ["Breakfast"],
        transport: "Private departure transfer",
        altitude: "150 m",
        notes: "Good final day for travelers who want historical context before leaving.",
        image: "",
        activities: [
          { listingTitle: "Lumbini Museum Learning Tour", notes: "Buddhist history and archaeology session." },
          { listingTitle: "Monastic Zone Tea House", notes: "Quiet tea break before departure." },
        ],
      },
    ],
    addOnTitles: ["World Peace Pagoda Sunset Visit", "Maya Devi Garden Cafe", "Lumbini Thakali Bhojanalaya"],
    isFeatured: true,
    isActive: true,
  },
  {
    title: "Buddhist Heritage Circuit Lumbini Tilaurakot Ramagrama",
    slug: "buddhist-heritage-circuit-lumbini-tilaurakot-ramagrama",
    shortDescription:
      "A deeper 4-day Buddhist heritage circuit connecting Lumbini's sacred core with Tilaurakot and Ramagrama Stupa.",
    description:
      "A richer heritage package for pilgrims, researchers, and culture-focused travelers. It starts with Lumbini's sacred core, adds monastery and museum context, then extends to Tilaurakot and Ramagrama for a broader Buddhist heritage story across the region.",
    location: "Lumbini",
    region: "Lumbini Province",
    pickupCity: "Gautam Buddha International Airport / Bhairahawa",
    dropoffCity: "Gautam Buddha International Airport / Bhairahawa",
    startDate: "2026-11-14",
    endDate: "2026-11-17",
    basePrice: 34500,
    discountPrice: 31800,
    rating: 4.9,
    currency: "NPR",
    capacity: 8,
    minGuests: 2,
    maxGuests: 8,
    coverImage: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1400&q=80",
    galleryImages: ["https://images.unsplash.com/photo-1501556424050-d4816356b73e?auto=format&fit=crop&w=1200&q=80"],
    videoUrl: "",
    included: [
      "3 nights hotel stay",
      "Daily breakfast",
      "Private regional vehicle",
      "Maya Devi Temple and Sacred Garden tour",
      "Lumbini Museum tour",
      "Tilaurakot archaeological day trip",
      "Ramagrama Stupa pilgrimage extension",
      "Local guide support",
    ],
    excluded: ["Lunch and dinner", "Entry fees not mentioned by local authority", "Personal offerings", "Travel insurance"],
    highlights: ["Lumbini birthplace", "Tilaurakot archaeology", "Ramagrama Stupa", "Museum context"],
    bestSeason: "October to March",
    difficulty: "Easy to Moderate",
    tripType: "Buddhist Heritage Circuit",
    cancellationPolicy: "Free cancellation up to 10 days before travel. 30% charge within 72 hours due to regional transfer holds.",
    paymentPolicy: "35% advance payment required to confirm vehicle, guide, and hotel arrangements.",
    faqs: [
      {
        question: "Is this good for academic or research-focused visitors?",
        answer: "Yes. It includes museum context, archaeology, and regional heritage extensions beyond the standard Lumbini visit.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Arrival and Lumbini sacred core",
        summary:
          "Arrive in Lumbini and begin with Maya Devi Temple, Ashoka Pillar, and the Sacred Garden.",
        hotelTitle: "Hotel Ananda Inn Lumbini",
        meals: ["Welcome tea"],
        transport: "Private airport transfer",
        altitude: "150 m",
        notes: "Gentle walking day after arrival.",
        image: "",
        activities: [
          { listingTitle: "Maya Devi Temple Sacred Walk", notes: "Birthplace site orientation." },
          { listingTitle: "Ashoka Pillar Heritage Briefing", notes: "Historical marker and inscription context." },
        ],
      },
      {
        dayNumber: 2,
        title: "Museum and monastic zone",
        summary:
          "Study Lumbini's museum context and visit selected monasteries in the development zone.",
        hotelTitle: "Hotel Ananda Inn Lumbini",
        meals: ["Breakfast"],
        transport: "Private local vehicle",
        altitude: "150 m",
        notes: "Good day for photos, notes, and slower interpretation.",
        image: "",
        activities: [
          { listingTitle: "Lumbini Museum Learning Tour", notes: "Historical and archaeological overview." },
          { listingTitle: "Lumbini Monastic Zone Cycling Tour", notes: "Selected monasteries and canal route." },
        ],
      },
      {
        dayNumber: 3,
        title: "Tilaurakot archaeological route",
        summary:
          "Travel to Tilaurakot for ancient Kapilvastu context and return to Lumbini by evening.",
        hotelTitle: "Hotel Ananda Inn Lumbini",
        meals: ["Breakfast"],
        transport: "Private regional vehicle",
        altitude: "150 m",
        notes: "Carry sun protection and water for open archaeological spaces.",
        image: "",
        activities: [
          { listingTitle: "Tilaurakot Archaeological Day Trip", notes: "Full regional heritage excursion." },
          { listingTitle: "Tilaurakot Heritage Tea Stop", notes: "Local refreshment stop." },
        ],
      },
      {
        dayNumber: 4,
        title: "Ramagrama Stupa and departure",
        summary:
          "Complete the Buddhist heritage circuit with Ramagrama Stupa before returning for departure.",
        hotelTitle: "Hotel Ananda Inn Lumbini",
        meals: ["Breakfast"],
        transport: "Private regional vehicle and airport drop",
        altitude: "150 m",
        notes: "Departure flights should be scheduled later in the day where possible.",
        image: "",
        activities: [{ listingTitle: "Ramagrama Stupa Pilgrimage Extension", notes: "Final pilgrimage extension." }],
      },
    ],
    addOnTitles: ["Peace Pagoda View Restaurant", "Three Vision Restaurant Lumbini", "Bhairahawa Gateway Hotel"],
    isFeatured: true,
    isActive: true,
  },
];

module.exports = { tripPackageSeeds };
