const locationSeeds = [
  {
    key: "lumbini",
    name: "Lumbini",
    province: "Lumbini",
    district: "Rupandehi",
    category: "Destination Hub",
    averageCost: 3200,
    latitude: 27.4698,
    longitude: 83.2752,
    description:
      "Lumbini is the birthplace of Siddhartha Gautama Buddha and one of Nepal's most important spiritual destinations, known for the Sacred Garden, Maya Devi Temple, monastic zones, museums, peace landmarks, and quiet pilgrimage routes.",
    image: "",
    images: [],
  },
  {
    key: "maya-devi-temple",
    parentKey: "lumbini",
    name: "Maya Devi Temple",
    province: "Lumbini",
    district: "Rupandehi",
    category: "Temple",
    averageCost: 800,
    latitude: 27.4693,
    longitude: 83.2754,
    description:
      "Maya Devi Temple marks the traditional birthplace of Buddha and contains sacred archaeological remains, the marker stone area, and one of Lumbini's most revered pilgrimage spaces.",
    image: "",
    images: [],
  },
  {
    key: "ashoka-pillar",
    parentKey: "lumbini",
    name: "Ashoka Pillar",
    province: "Lumbini",
    district: "Rupandehi",
    category: "Heritage",
    averageCost: 300,
    latitude: 27.4691,
    longitude: 83.2751,
    description:
      "The Ashoka Pillar is an ancient stone inscription associated with Emperor Ashoka's pilgrimage to Lumbini and provides historical evidence of the site's sacred significance.",
    image: "",
    images: [],
  },
  {
    key: "sacred-garden",
    parentKey: "lumbini",
    name: "Sacred Garden",
    province: "Lumbini",
    district: "Rupandehi",
    category: "Cultural",
    averageCost: 500,
    latitude: 27.4697,
    longitude: 83.2764,
    description:
      "The Sacred Garden surrounds the Maya Devi Temple area with ponds, trees, archaeological remains, and peaceful walking paths for pilgrims and visitors.",
    image: "",
    images: [],
  },
  {
    key: "world-peace-pagoda-lumbini",
    parentKey: "lumbini",
    name: "World Peace Pagoda Lumbini",
    province: "Lumbini",
    district: "Rupandehi",
    category: "Stupa",
    averageCost: 600,
    latitude: 27.4867,
    longitude: 83.2846,
    description:
      "The World Peace Pagoda is a bright white stupa built as a symbol of peace and reflection, located north of the main sacred complex.",
    image: "",
    images: [],
  },
  {
    key: "lumbini-monastic-zone",
    parentKey: "lumbini",
    name: "Lumbini Monastic Zone",
    province: "Lumbini",
    district: "Rupandehi",
    category: "Monastery",
    averageCost: 1000,
    latitude: 27.4827,
    longitude: 83.2769,
    description:
      "The Monastic Zone contains monasteries built by Buddhist communities from many countries, offering architecture, rituals, meditation spaces, and global Buddhist cultural diversity.",
    image: "",
    images: [],
  },
  {
    key: "lumbini-museum",
    parentKey: "lumbini",
    name: "Lumbini Museum",
    province: "Lumbini",
    district: "Rupandehi",
    category: "Museum",
    averageCost: 500,
    latitude: 27.4848,
    longitude: 83.2761,
    description:
      "Lumbini Museum presents Buddhist history, archaeological context, religious art, and learning material related to the life of Buddha and the wider Lumbini region.",
    image: "",
    images: [],
  },
  {
    key: "royal-thai-monastery",
    parentKey: "lumbini",
    name: "Royal Thai Monastery",
    province: "Lumbini",
    district: "Rupandehi",
    category: "Monastery",
    averageCost: 600,
    latitude: 27.4797,
    longitude: 83.2805,
    description:
      "The Royal Thai Monastery is known for its elegant white architecture, quiet courtyards, and Thai Buddhist design within Lumbini's monastic landscape.",
    image: "",
    images: [],
  },
  {
    key: "german-monastery",
    parentKey: "lumbini",
    name: "German Monastery",
    province: "Lumbini",
    district: "Rupandehi",
    category: "Monastery",
    averageCost: 700,
    latitude: 27.4808,
    longitude: 83.2715,
    description:
      "The German Monastery area is admired for colorful Buddhist art, detailed murals, garden spaces, and a calm atmosphere for visitors walking the western monastic zone.",
    image: "",
    images: [],
  },
  {
    key: "myanmar-golden-temple",
    parentKey: "lumbini",
    name: "Myanmar Golden Temple",
    province: "Lumbini",
    district: "Rupandehi",
    category: "Temple",
    averageCost: 500,
    latitude: 27.4773,
    longitude: 83.2817,
    description:
      "The Myanmar Golden Temple is one of Lumbini's visually striking monasteries, with golden features, Burmese Buddhist influence, and easy access from the central monastic area.",
    image: "",
    images: [],
  },
  {
    key: "tilaurakot",
    parentKey: "lumbini",
    name: "Tilaurakot",
    province: "Lumbini",
    district: "Kapilvastu",
    category: "Archaeological",
    averageCost: 2500,
    latitude: 27.5725,
    longitude: 83.0528,
    description:
      "Tilaurakot is an important archaeological site associated with ancient Kapilavastu and the early life context of Buddha before renunciation.",
    image: "",
    images: [],
  },
  {
    key: "ramagrama-stupa",
    parentKey: "lumbini",
    name: "Ramagrama Stupa",
    province: "Lumbini",
    district: "Nawalparasi West",
    category: "Stupa",
    averageCost: 3000,
    latitude: 27.5299,
    longitude: 83.6732,
    description:
      "Ramagrama Stupa is a significant Buddhist pilgrimage site traditionally associated with relics of Buddha, visited as a meaningful extension from Lumbini.",
    image: "",
    images: [],
  },
];

const listingSeeds = [
  {
    type: "activity",
    title: "Maya Devi Temple Sacred Walk",
    description: "Guided sacred walk around Maya Devi Temple, marker stone area, nativity sculpture, and temple-side heritage remains.",
    location: { name: "Maya Devi Temple", address: "Sacred Garden core, Lumbini", district: "Rupandehi", province: "Lumbini", lat: 27.4693, lng: 83.2754 },
    pricePerUnit: 1000,
    capacity: 15,
    amenities: ["Licensed guide", "Sacred Garden orientation", "Pilgrimage etiquette briefing"],
    rating: 4.9,
  },
  {
    type: "activity",
    title: "Ashoka Pillar Heritage Briefing",
    description: "Short interpretive stop focused on the Ashoka inscription, archaeological context, and Lumbini's historical importance.",
    location: { name: "Ashoka Pillar", address: "Maya Devi Temple complex, Lumbini", district: "Rupandehi", province: "Lumbini", lat: 27.4691, lng: 83.2751 },
    pricePerUnit: 500,
    capacity: 20,
    amenities: ["Guide", "Heritage explanation", "Photo stop"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Sacred Garden Mindful Walk",
    description: "Slow-paced walk through the Sacred Garden, pond area, archaeological remains, and quiet meditation corners.",
    location: { name: "Sacred Garden", address: "Sacred Garden pathways, Lumbini", district: "Rupandehi", province: "Lumbini", lat: 27.4697, lng: 83.2764 },
    pricePerUnit: 800,
    capacity: 12,
    amenities: ["Mindful guide", "Quiet route", "Reflection stops"],
    rating: 4.8,
  },
  {
    type: "activity",
    title: "Lumbini Monastic Zone Cycling Tour",
    description: "Bicycle-supported tour through eastern and western monastic zones with selected monastery stops.",
    location: { name: "Lumbini Monastic Zone", address: "Lumbini Development Zone", district: "Rupandehi", province: "Lumbini", lat: 27.4827, lng: 83.2769 },
    pricePerUnit: 1500,
    capacity: 10,
    amenities: ["Cycle rental", "Guide", "Water break", "Monastery stops"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "World Peace Pagoda Sunset Visit",
    description: "Late-afternoon visit to the World Peace Pagoda with quiet time and sunset-side photography.",
    location: { name: "World Peace Pagoda Lumbini", address: "North Lumbini monastic area", district: "Rupandehi", province: "Lumbini", lat: 27.4867, lng: 83.2846 },
    pricePerUnit: 700,
    capacity: 15,
    amenities: ["Transfer support", "Photo stop", "Quiet reflection time"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Lumbini Museum Learning Tour",
    description: "Museum-focused guided session introducing Buddhist art, archaeology, and Lumbini's historical context.",
    location: { name: "Lumbini Museum", address: "Museum area, Lumbini Development Zone", district: "Rupandehi", province: "Lumbini", lat: 27.4848, lng: 83.2761 },
    pricePerUnit: 900,
    capacity: 20,
    amenities: ["Museum entry coordination", "Guide", "Indoor learning route"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Royal Thai Monastery Architecture Stop",
    description: "Short cultural visit to the Royal Thai Monastery focusing on Thai Buddhist design, courtyards, and quiet temple etiquette.",
    location: { name: "Royal Thai Monastery", address: "Eastern Monastic Zone, Lumbini", district: "Rupandehi", province: "Lumbini", lat: 27.4797, lng: 83.2805 },
    pricePerUnit: 600,
    capacity: 15,
    amenities: ["Guide", "Architecture briefing", "Photo stops"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "German Monastery Art and Garden Walk",
    description: "Visit the German Monastery area for Buddhist murals, garden spaces, and western monastic zone architecture.",
    location: { name: "German Monastery", address: "Western Monastic Zone, Lumbini", district: "Rupandehi", province: "Lumbini", lat: 27.4808, lng: 83.2715 },
    pricePerUnit: 700,
    capacity: 12,
    amenities: ["Guide", "Garden route", "Art interpretation"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Myanmar Golden Temple Visit",
    description: "Cultural stop at the Myanmar Golden Temple with Burmese Buddhist architecture and peaceful compound visit.",
    location: { name: "Myanmar Golden Temple", address: "Eastern Monastic Zone, Lumbini", district: "Rupandehi", province: "Lumbini", lat: 27.4773, lng: 83.2817 },
    pricePerUnit: 600,
    capacity: 15,
    amenities: ["Guide", "Temple briefing", "Photo stop"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Tilaurakot Archaeological Day Trip",
    description: "Day excursion to Tilaurakot for ancient Kapilvastu history, ruins, museum-side interpretation, and Buddha life context.",
    location: { name: "Tilaurakot", address: "Tilaurakot archaeological site, Kapilvastu", district: "Kapilvastu", province: "Lumbini", lat: 27.5725, lng: 83.0528 },
    pricePerUnit: 4200,
    capacity: 10,
    amenities: ["Private transfer", "Guide", "Archaeological briefing", "Water"],
    rating: 4.8,
  },
  {
    type: "activity",
    title: "Ramagrama Stupa Pilgrimage Extension",
    description: "Meaningful pilgrimage extension from Lumbini to Ramagrama Stupa with guide and private transfer support.",
    location: { name: "Ramagrama Stupa", address: "Ramagrama heritage area", district: "Nawalparasi West", province: "Lumbini", lat: 27.5299, lng: 83.6732 },
    pricePerUnit: 4800,
    capacity: 8,
    amenities: ["Private transfer", "Guide", "Pilgrimage stop", "Tea break"],
    rating: 4.7,
  },
  {
    type: "hotel",
    title: "Buddha Maya Garden Hotel",
    description: "Peaceful hotel near the Lumbini sacred area with garden surroundings and comfortable pilgrimage stay facilities.",
    location: { name: "Maya Devi Temple", address: "Lumbini Bazaar Road near Sacred Garden", district: "Rupandehi", province: "Lumbini", lat: 27.4723, lng: 83.278 },
    pricePerUnit: 6500,
    capacity: 2,
    amenities: ["Garden", "Restaurant", "Wi-Fi", "Airport transfer"],
    rating: 4.5,
  },
  {
    type: "hotel",
    title: "Lumbini Hokke Hotel",
    description: "Japanese-inspired stay inside the Lumbini area, suitable for quiet pilgrimage and monastery-focused visits.",
    location: { name: "Lumbini Monastic Zone", address: "Lumbini Development Zone", district: "Rupandehi", province: "Lumbini", lat: 27.4788, lng: 83.2762 },
    pricePerUnit: 7200,
    capacity: 2,
    amenities: ["Quiet setting", "Restaurant", "Garden", "Wi-Fi"],
    rating: 4.4,
  },
  {
    type: "hotel",
    title: "Hotel Ananda Inn Lumbini",
    description: "Practical midrange stay close to the pilgrimage zone with simple access to Maya Devi Temple and local restaurants.",
    location: { name: "Sacred Garden", address: "Mahilwar, Lumbini", district: "Rupandehi", province: "Lumbini", lat: 27.4717, lng: 83.2805 },
    pricePerUnit: 4200,
    capacity: 2,
    amenities: ["Restaurant", "Wi-Fi", "Hot shower", "Parking"],
    rating: 4.2,
  },
  {
    type: "hotel",
    title: "Lumbini Buddha Garden Resort",
    description: "Relaxed resort-style property for families and longer spiritual stays around Lumbini.",
    location: { name: "World Peace Pagoda Lumbini", address: "Lumbini approach road", district: "Rupandehi", province: "Lumbini", lat: 27.4791, lng: 83.288 },
    pricePerUnit: 5800,
    capacity: 2,
    amenities: ["Garden", "Restaurant", "Family rooms", "Parking"],
    rating: 4.3,
  },
  {
    type: "hotel",
    title: "Bhairahawa Gateway Hotel",
    description: "Convenient hotel near Bhairahawa airport for travelers arriving late or connecting to Lumbini by road.",
    location: { name: "Lumbini", address: "Bhairahawa-Lumbini corridor", district: "Rupandehi", province: "Lumbini", lat: 27.5057, lng: 83.4493 },
    pricePerUnit: 5000,
    capacity: 2,
    amenities: ["Airport access", "Restaurant", "Wi-Fi", "Parking"],
    rating: 4.2,
  },
  {
    type: "restaurant",
    title: "Lumbini Thakali Bhojanalaya",
    description: "Reliable local meal stop serving Nepali thali, vegetarian options, tea, and group-friendly lunch service.",
    location: { name: "Lumbini", address: "Mahilwar market, Lumbini", district: "Rupandehi", province: "Lumbini", lat: 27.4712, lng: 83.2811 },
    pricePerUnit: 600,
    capacity: 35,
    amenities: ["Nepali thali", "Vegetarian options", "Group seating", "Tea"],
    rating: 4.3,
  },
  {
    type: "restaurant",
    title: "Three Vision Restaurant Lumbini",
    description: "Traveler-friendly restaurant offering Nepali, Indian, Chinese, and simple continental dishes near the pilgrimage zone.",
    location: { name: "Sacred Garden", address: "Lumbini Bazaar area", district: "Rupandehi", province: "Lumbini", lat: 27.4708, lng: 83.2802 },
    pricePerUnit: 850,
    capacity: 40,
    amenities: ["Multi-cuisine", "Family seating", "Vegetarian menu", "Wi-Fi"],
    rating: 4.4,
  },
  {
    type: "restaurant",
    title: "Maya Devi Garden Cafe",
    description: "Calm cafe-style stop for tea, coffee, snacks, and light meals after visiting the Sacred Garden.",
    location: { name: "Maya Devi Temple", address: "Near Maya Devi Temple approach", district: "Rupandehi", province: "Lumbini", lat: 27.4701, lng: 83.2768 },
    pricePerUnit: 450,
    capacity: 22,
    amenities: ["Coffee", "Tea", "Snacks", "Quiet seating"],
    rating: 4.2,
  },
  {
    type: "restaurant",
    title: "Peace Pagoda View Restaurant",
    description: "Simple meal and tea stop useful for visitors exploring the World Peace Pagoda and north monastic side.",
    location: { name: "World Peace Pagoda Lumbini", address: "Peace Pagoda access road", district: "Rupandehi", province: "Lumbini", lat: 27.4862, lng: 83.284 },
    pricePerUnit: 650,
    capacity: 28,
    amenities: ["Tea", "Lunch", "Group tables", "View stop"],
    rating: 4.1,
  },
  {
    type: "cafe",
    title: "Monastic Zone Tea House",
    description: "Small tea-house style cafe for cycling breaks around the monastery route.",
    location: { name: "Lumbini Monastic Zone", address: "Central canal route, Lumbini", district: "Rupandehi", province: "Lumbini", lat: 27.4819, lng: 83.2768 },
    pricePerUnit: 350,
    capacity: 18,
    amenities: ["Tea", "Cold drinks", "Light snacks", "Cycle parking"],
    rating: 4.1,
  },
  {
    type: "cafe",
    title: "Tilaurakot Heritage Tea Stop",
    description: "Local tea and snack stop for travelers visiting the Tilaurakot archaeological route.",
    location: { name: "Tilaurakot", address: "Tilaurakot approach area", district: "Kapilvastu", province: "Lumbini", lat: 27.5721, lng: 83.0531 },
    pricePerUnit: 300,
    capacity: 16,
    amenities: ["Tea", "Snacks", "Local seating"],
    rating: 4.0,
  },
];

const nearbyRecommendations = [
  { name: "Bhairahawa", distanceKm: 22, mainActivity: "Airport access, city hotels, and regional food stops" },
  { name: "Butwal", distanceKm: 45, mainActivity: "Urban stopover, Siddha Baba route, and shopping" },
  { name: "Kapilvastu", distanceKm: 28, mainActivity: "Tilaurakot archaeology and Buddha life heritage" },
  { name: "Devdaha", distanceKm: 35, mainActivity: "Buddhist heritage extension and local culture" },
  { name: "Ramagrama", distanceKm: 70, mainActivity: "Stupa pilgrimage and relic heritage route" },
];

module.exports = { locationSeeds, listingSeeds, nearbyRecommendations };
