const locationSeeds = [
  {
    key: "mustang",
    name: "Mustang",
    province: "Gandaki",
    district: "Mustang",
    category: "Destination Hub",
    averageCost: 5500,
    latitude: 28.9985,
    longitude: 83.8473,
    description:
      "Mustang is Nepal's high-altitude desert region known for dramatic landscapes, Tibetan-influenced culture, walled settlements, monasteries, cave heritage, and long scenic road journeys.",
    image: "",
    images: [],
  },
  {
    key: "jomsom",
    parentKey: "mustang",
    name: "Jomsom",
    province: "Gandaki",
    district: "Mustang",
    category: "Town",
    averageCost: 3500,
    latitude: 28.7815,
    longitude: 83.723,
    description:
      "Jomsom is Mustang's best-known transit town with mountain views, windswept lanes, airport access, apple products, and route connections deeper into the district.",
    image: "",
    images: [],
  },
  {
    key: "kagbeni",
    parentKey: "mustang",
    name: "Kagbeni",
    province: "Gandaki",
    district: "Mustang",
    category: "Cultural",
    averageCost: 2800,
    latitude: 28.8398,
    longitude: 83.7722,
    description:
      "Kagbeni is a striking gateway settlement with mud-brick alleys, monastery culture, river confluence views, and one of Mustang's most photogenic village settings.",
    image: "",
    images: [],
  },
  {
    key: "muktinath-temple",
    parentKey: "mustang",
    name: "Muktinath Temple",
    province: "Gandaki",
    district: "Mustang",
    category: "Temple",
    averageCost: 2500,
    latitude: 28.8167,
    longitude: 83.8717,
    description:
      "A major pilgrimage site for both Hindus and Buddhists, Muktinath offers sacred shrines, eternal flames, mountain scenery, and high-altitude spiritual atmosphere.",
    image: "",
    images: [],
  },
  {
    key: "marpha",
    parentKey: "mustang",
    name: "Marpha",
    province: "Gandaki",
    district: "Mustang",
    category: "Cultural",
    averageCost: 2200,
    latitude: 28.7471,
    longitude: 83.6907,
    description:
      "Marpha is a charming whitewashed village famous for apple orchards, tidy stone lanes, monastery culture, and one of the most pleasant short stops in lower Mustang.",
    image: "",
    images: [],
  },
  {
    key: "lubra-village",
    parentKey: "mustang",
    name: "Lupra Village",
    province: "Gandaki",
    district: "Mustang",
    category: "Village",
    averageCost: 2400,
    latitude: 28.7649,
    longitude: 83.6947,
    description:
      "Lupra is a quieter Bon-influenced settlement near Jomsom with sparse desert scenery, traditional homes, and a more offbeat cultural experience.",
    image: "",
    images: [],
  },
  {
    key: "dhumba-lake",
    parentKey: "mustang",
    name: "Dhumba Lake",
    province: "Gandaki",
    district: "Mustang",
    category: "Lake",
    averageCost: 1200,
    latitude: 28.7924,
    longitude: 83.7312,
    description:
      "A calm alpine lake near Jomsom visited for short walks, reflective mountain views, and a more peaceful break from Mustang's road-based travel rhythm.",
    image: "",
    images: [],
  },
  {
    key: "tetang-village",
    parentKey: "mustang",
    name: "Tetang Village",
    province: "Gandaki",
    district: "Mustang",
    category: "Village",
    averageCost: 1800,
    latitude: 28.8428,
    longitude: 83.8255,
    description:
      "Tetang is a smaller traditional village near Muktinath known for its dry mountain setting, cultural texture, and slower local feel.",
    image: "",
    images: [],
  },
  {
    key: "jharkot-monastery-area",
    parentKey: "mustang",
    name: "Jharkot Monastery Area",
    province: "Gandaki",
    district: "Mustang",
    category: "Monastery",
    averageCost: 1600,
    latitude: 28.8138,
    longitude: 83.8642,
    description:
      "Jharkot combines a hillside village setting with monastery heritage, old architecture, and expansive Mustang valley views on the route to Muktinath.",
    image: "",
    images: [],
  },
  {
    key: "chhusang",
    parentKey: "mustang",
    name: "Chhusang",
    province: "Gandaki",
    district: "Mustang",
    category: "Nature",
    averageCost: 2000,
    latitude: 28.7827,
    longitude: 83.8825,
    description:
      "Chhusang offers red cliff scenery, river valley views, and a dramatic landscape character that makes it one of Mustang's visually memorable stops.",
    image: "",
    images: [],
  },
  {
    key: "lo-manthang-viewpoint",
    parentKey: "mustang",
    name: "Lo Manthang Viewpoint",
    province: "Gandaki",
    district: "Mustang",
    category: "Viewpoint",
    averageCost: 4200,
    latitude: 29.1815,
    longitude: 83.9648,
    description:
      "A high-value scenic viewpoint associated with upper Mustang journeys, showing the walled settlement landscape and the dramatic trans-Himalayan character of the region.",
    image: "",
    images: [],
  },
  {
    key: "choser-cave-area",
    parentKey: "mustang",
    name: "Chhoser Cave Area",
    province: "Gandaki",
    district: "Mustang",
    category: "Heritage",
    averageCost: 4500,
    latitude: 29.2094,
    longitude: 84.0457,
    description:
      "The Chhoser cave area is known for ancient sky caves, eroded cliff formations, and one of Mustang's most distinctive heritage landscapes.",
    image: "",
    images: [],
  },
];

module.exports = { locationSeeds };
