const locationSeeds = [
  {
    key: "mustang",
    name: "Mustang",
    province: "Gandaki",
    district: "Mustang",
    category: "Destination Hub",
    averageCost: 5500,
    latitude: 28.9985,
    longitude: 83.8473,
    description:
      "Mustang is Nepal's high-altitude desert region known for dramatic landscapes, Tibetan-influenced culture, walled settlements, monasteries, cave heritage, and long scenic road journeys.",
    image: "",
    images: [],
  },
  {
    key: "jomsom",
    parentKey: "mustang",
    name: "Jomsom",
    province: "Gandaki",
    district: "Mustang",
    category: "Town",
    averageCost: 3500,
    latitude: 28.7815,
    longitude: 83.723,
    description:
      "Jomsom is Mustang's best-known transit town with mountain views, windswept lanes, airport access, apple products, and route connections deeper into the district.",
    image: "",
    images: [],
  },
  {
    key: "kagbeni",
    parentKey: "mustang",
    name: "Kagbeni",
    province: "Gandaki",
    district: "Mustang",
    category: "Cultural",
    averageCost: 2800,
    latitude: 28.8398,
    longitude: 83.7722,
    description:
      "Kagbeni is a striking gateway settlement with mud-brick alleys, monastery culture, river confluence views, and one of Mustang's most photogenic village settings.",
    image: "",
    images: [],
  },
  {
    key: "muktinath-temple",
    parentKey: "mustang",
    name: "Muktinath Temple",
    province: "Gandaki",
    district: "Mustang",
    category: "Temple",
    averageCost: 2500,
    latitude: 28.8167,
    longitude: 83.8717,
    description:
      "A major pilgrimage site for both Hindus and Buddhists, Muktinath offers sacred shrines, eternal flames, mountain scenery, and high-altitude spiritual atmosphere.",
    image: "",
    images: [],
  },
  {
    key: "marpha",
    parentKey: "mustang",
    name: "Marpha",
    province: "Gandaki",
    district: "Mustang",
    category: "Cultural",
    averageCost: 2200,
    latitude: 28.7471,
    longitude: 83.6907,
    description:
      "Marpha is a charming whitewashed village famous for apple orchards, tidy stone lanes, monastery culture, and one of the most pleasant short stops in lower Mustang.",
    image: "",
    images: [],
  },
  {
    key: "lubra-village",
    parentKey: "mustang",
    name: "Lupra Village",
    province: "Gandaki",
    district: "Mustang",
    category: "Village",
    averageCost: 2400,
    latitude: 28.7649,
    longitude: 83.6947,
    description:
      "Lupra is a quieter Bon-influenced settlement near Jomsom with sparse desert scenery, traditional homes, and a more offbeat cultural experience.",
    image: "",
    images: [],
  },
  {
    key: "dhumba-lake",
    parentKey: "mustang",
    name: "Dhumba Lake",
    province: "Gandaki",
    district: "Mustang",
    category: "Lake",
    averageCost: 1200,
    latitude: 28.7924,
    longitude: 83.7312,
    description:
      "A calm alpine lake near Jomsom visited for short walks, reflective mountain views, and a more peaceful break from Mustang's road-based travel rhythm.",
    image: "",
    images: [],
  },
  {
    key: "tetang-village",
    parentKey: "mustang",
    name: "Tetang Village",
    province: "Gandaki",
    district: "Mustang",
    category: "Village",
    averageCost: 1800,
    latitude: 28.8428,
    longitude: 83.8255,
    description:
      "Tetang is a smaller traditional village near Muktinath known for its dry mountain setting, cultural texture, and slower local feel.",
    image: "",
    images: [],
  },
  {
    key: "jharkot-monastery-area",
    parentKey: "mustang",
    name: "Jharkot Monastery Area",
    province: "Gandaki",
    district: "Mustang",
    category: "Monastery",
    averageCost: 1600,
    latitude: 28.8138,
    longitude: 83.8642,
    description:
      "Jharkot combines a hillside village setting with monastery heritage, old architecture, and expansive Mustang valley views on the route to Muktinath.",
    image: "",
    images: [],
  },
  {
    key: "chhusang",
    parentKey: "mustang",
    name: "Chhusang",
    province: "Gandaki",
    district: "Mustang",
    category: "Nature",
    averageCost: 2000,
    latitude: 28.7827,
    longitude: 83.8825,
    description:
      "Chhusang offers red cliff scenery, river valley views, and a dramatic landscape character that makes it one of Mustang's visually memorable stops.",
    image: "",
    images: [],
  },
  {
    key: "lo-manthang-viewpoint",
    parentKey: "mustang",
    name: "Lo Manthang Viewpoint",
    province: "Gandaki",
    district: "Mustang",
    category: "Viewpoint",
    averageCost: 4200,
    latitude: 29.1815,
    longitude: 83.9648,
    description:
      "A high-value scenic viewpoint associated with upper Mustang journeys, showing the walled settlement landscape and the dramatic trans-Himalayan character of the region.",
    image: "",
    images: [],
  },
  {
    key: "choser-cave-area",
    parentKey: "mustang",
    name: "Chhoser Cave Area",
    province: "Gandaki",
    district: "Mustang",
    category: "Heritage",
    averageCost: 4500,
    latitude: 29.2094,
    longitude: 84.0457,
    description:
      "The Chhoser cave area is known for ancient sky caves, eroded cliff formations, and one of Mustang's most distinctive heritage landscapes.",
    image: "",
    images: [],
  },
];

const listingSeeds = [
  {
    type: "activity",
    title: "Kagbeni Old Village Heritage Walk",
    description: "Guided walk through Kagbeni's mud-brick lanes, chortens, prayer wheels, and monastery-side alleys.",
    location: { name: "Kagbeni", address: "Old Kagbeni village core", district: "Mustang", province: "Gandaki", lat: 28.8398, lng: 83.7722 },
    pricePerUnit: 1200,
    capacity: 12,
    amenities: ["Local guide", "Monastery orientation", "Photo stops"],
    rating: 4.8,
  },
  {
    type: "activity",
    title: "Muktinath Temple Darshan Transfer",
    description: "Pilgrimage-focused return transfer and guided orientation around the Muktinath temple complex.",
    location: { name: "Muktinath Temple", address: "Muktinath temple entrance area", district: "Mustang", province: "Gandaki", lat: 28.8167, lng: 83.8717 },
    pricePerUnit: 2500,
    capacity: 8,
    amenities: ["Jeep transfer", "Temple timing support", "High-altitude guidance"],
    rating: 4.9,
  },
  {
    type: "activity",
    title: "Marpha Apple Village Walk",
    description: "Cultural walk through Marpha's whitewashed lanes, apple orchards, local shops, and monastery steps.",
    location: { name: "Marpha", address: "Marpha village center", district: "Mustang", province: "Gandaki", lat: 28.7471, lng: 83.6907 },
    pricePerUnit: 900,
    capacity: 15,
    amenities: ["Village guide", "Apple product tasting", "Monastery viewpoint"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Jomsom Wind Valley Orientation",
    description: "Short guided Jomsom orientation covering the riverside, market lane, airport area, and mountain-view points.",
    location: { name: "Jomsom", address: "Jomsom bazaar and Kali Gandaki riverside", district: "Mustang", province: "Gandaki", lat: 28.7815, lng: 83.723 },
    pricePerUnit: 700,
    capacity: 15,
    amenities: ["Local guide", "Riverside walk", "Market stop"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Dhumba Lake Short Hike",
    description: "Gentle hike from Jomsom side to Dhumba Lake for quiet water views and Nilgiri backdrop.",
    location: { name: "Dhumba Lake", address: "Dhumba Lake trail above Jomsom", district: "Mustang", province: "Gandaki", lat: 28.7924, lng: 83.7312 },
    pricePerUnit: 1600,
    capacity: 10,
    amenities: ["Guide", "Water break", "Viewpoint stops"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Jharkot Monastery Cultural Stop",
    description: "Cultural visit to Jharkot village and monastery area on the Muktinath route.",
    location: { name: "Jharkot Monastery Area", address: "Jharkot village trail", district: "Mustang", province: "Gandaki", lat: 28.8138, lng: 83.8642 },
    pricePerUnit: 1000,
    capacity: 12,
    amenities: ["Village walk", "Monastery briefing", "View terrace"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Lupra Bon Village Experience",
    description: "Offbeat cultural visit to Lupra for Bon-influenced heritage, dry valley scenery, and traditional settlement life.",
    location: { name: "Lupra Village", address: "Lupra village route near Jomsom", district: "Mustang", province: "Gandaki", lat: 28.7649, lng: 83.6947 },
    pricePerUnit: 2200,
    capacity: 8,
    amenities: ["Local guide", "Cultural briefing", "Jeep coordination"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Chhusang Red Cliff Jeep Stop",
    description: "Scenic jeep-supported stop around Chhusang's red cliffs, river valley, and dramatic desert formations.",
    location: { name: "Chhusang", address: "Chhusang valley road viewpoint", district: "Mustang", province: "Gandaki", lat: 28.7827, lng: 83.8825 },
    pricePerUnit: 1800,
    capacity: 10,
    amenities: ["Jeep stop", "Photo points", "Guide"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Tetang Village Cultural Detour",
    description: "Quiet village detour for travelers who want a slower look at Mustang settlement life near Muktinath.",
    location: { name: "Tetang Village", address: "Tetang village trail", district: "Mustang", province: "Gandaki", lat: 28.8428, lng: 83.8255 },
    pricePerUnit: 1400,
    capacity: 10,
    amenities: ["Village walk", "Guide", "Photo stops"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Lo Manthang Walled City Walk",
    description: "Upper Mustang cultural walk around Lo Manthang's walled settlement, monasteries, alleys, and palace-side views.",
    location: { name: "Lo Manthang Viewpoint", address: "Lo Manthang settlement and viewpoint area", district: "Mustang", province: "Gandaki", lat: 29.1815, lng: 83.9648 },
    pricePerUnit: 3500,
    capacity: 10,
    amenities: ["Upper Mustang guide", "Monastery orientation", "Viewpoint walk"],
    rating: 4.9,
  },
  {
    type: "activity",
    title: "Chhoser Sky Cave Exploration",
    description: "Guided exploration of the Chhoser cave area with ancient cliff dwellings and trans-Himalayan scenery.",
    location: { name: "Chhoser Cave Area", address: "Chhoser cave heritage area", district: "Mustang", province: "Gandaki", lat: 29.2094, lng: 84.0457 },
    pricePerUnit: 4200,
    capacity: 8,
    amenities: ["Guide", "Cave entry coordination", "Jeep support"],
    rating: 4.9,
  },
  {
    type: "hotel",
    title: "Hotel Oms Home Jomsom",
    description: "Comfortable Jomsom base with mountain views, warm dining, and good access to onward Mustang routes.",
    location: { name: "Jomsom", address: "Jomsom bazaar area", district: "Mustang", province: "Gandaki", lat: 28.7821, lng: 83.7235 },
    pricePerUnit: 5500,
    capacity: 2,
    amenities: ["Wi-Fi", "Restaurant", "Hot shower", "Mountain view"],
    rating: 4.5,
  },
  {
    type: "hotel",
    title: "Hotel Yac Donalds Kagbeni",
    description: "Atmospheric Kagbeni stay close to the old village lanes and gateway route toward Upper Mustang.",
    location: { name: "Kagbeni", address: "Kagbeni village center", district: "Mustang", province: "Gandaki", lat: 28.8402, lng: 83.7726 },
    pricePerUnit: 4200,
    capacity: 2,
    amenities: ["Restaurant", "Hot shower", "Village view", "Wi-Fi"],
    rating: 4.4,
  },
  {
    type: "hotel",
    title: "Paradise Guest House Marpha",
    description: "Cozy Marpha guesthouse for apple village stays, local food, and lower Mustang acclimatization.",
    location: { name: "Marpha", address: "Marpha main lane", district: "Mustang", province: "Gandaki", lat: 28.7473, lng: 83.6909 },
    pricePerUnit: 2800,
    capacity: 2,
    amenities: ["Local meals", "Hot shower", "Apple products", "Wi-Fi"],
    rating: 4.3,
  },
  {
    type: "hotel",
    title: "Muktinath Grand Hotel",
    description: "Pilgrim-friendly stay near Ranipauwa with practical access to Muktinath temple.",
    location: { name: "Muktinath Temple", address: "Ranipauwa, Muktinath area", district: "Mustang", province: "Gandaki", lat: 28.8191, lng: 83.8689 },
    pricePerUnit: 4800,
    capacity: 2,
    amenities: ["Hot shower", "Restaurant", "Temple transfer help", "Heating blankets"],
    rating: 4.2,
  },
  {
    type: "hotel",
    title: "Lo Manthang Heritage Lodge",
    description: "Upper Mustang lodge-style stay for cultural travelers visiting the walled city and Chhoser caves.",
    location: { name: "Lo Manthang Viewpoint", address: "Lo Manthang settlement area", district: "Mustang", province: "Gandaki", lat: 29.1817, lng: 83.965 },
    pricePerUnit: 6500,
    capacity: 2,
    amenities: ["Local meals", "Guide support", "Warm bedding", "Cultural location"],
    rating: 4.6,
  },
  {
    type: "restaurant",
    title: "Jomsom Thakali Kitchen",
    description: "Reliable Thakali meal stop in Jomsom for dal bhat, buckwheat sides, and apple dessert options.",
    location: { name: "Jomsom", address: "Jomsom bazaar", district: "Mustang", province: "Gandaki", lat: 28.7818, lng: 83.7232 },
    pricePerUnit: 700,
    capacity: 35,
    amenities: ["Thakali set", "Vegetarian options", "Tea", "Group seating"],
    rating: 4.6,
  },
  {
    type: "restaurant",
    title: "Marpha Apple Garden Restaurant",
    description: "Marpha food stop known for apple pie, apple brandy tasting options, and simple Mustang meals.",
    location: { name: "Marpha", address: "Marpha village lane", district: "Mustang", province: "Gandaki", lat: 28.7472, lng: 83.691 },
    pricePerUnit: 650,
    capacity: 24,
    amenities: ["Apple pie", "Local lunch", "Tea", "Indoor seating"],
    rating: 4.5,
  },
  {
    type: "restaurant",
    title: "Kagbeni Yak Cafe",
    description: "Traveler-friendly cafe in Kagbeni serving tea, soup, momos, and high-altitude comfort snacks.",
    location: { name: "Kagbeni", address: "Kagbeni old-route cafe lane", district: "Mustang", province: "Gandaki", lat: 28.8397, lng: 83.7721 },
    pricePerUnit: 550,
    capacity: 20,
    amenities: ["Tea", "Momos", "Soups", "Wi-Fi"],
    rating: 4.4,
  },
  {
    type: "restaurant",
    title: "Muktinath Pilgrim Bhojanalaya",
    description: "Simple vegetarian-friendly meal stop for temple visitors and road travelers around Ranipauwa.",
    location: { name: "Muktinath Temple", address: "Ranipauwa market area", district: "Mustang", province: "Gandaki", lat: 28.8183, lng: 83.8695 },
    pricePerUnit: 500,
    capacity: 30,
    amenities: ["Vegetarian meals", "Tea", "Quick service", "Group seating"],
    rating: 4.2,
  },
  {
    type: "cafe",
    title: "Lo Manthang Tea House Cafe",
    description: "Warm tea-house cafe for butter tea, soup, noodles, and rest breaks during Upper Mustang exploration.",
    location: { name: "Lo Manthang Viewpoint", address: "Lo Manthang main settlement", district: "Mustang", province: "Gandaki", lat: 29.1812, lng: 83.9644 },
    pricePerUnit: 600,
    capacity: 18,
    amenities: ["Butter tea", "Noodles", "Soup", "Warm seating"],
    rating: 4.5,
  },
  {
    type: "cafe",
    title: "Dhumba Lake Tea Stop",
    description: "Small local tea stop useful for Dhumba Lake walkers returning toward Jomsom.",
    location: { name: "Dhumba Lake", address: "Dhumba Lake trail return point", district: "Mustang", province: "Gandaki", lat: 28.7921, lng: 83.7307 },
    pricePerUnit: 300,
    capacity: 12,
    amenities: ["Tea", "Light snacks", "View rest stop"],
    rating: 4.1,
  },
];

const nearbyRecommendations = [
  { name: "Tatopani", distanceKm: 52, mainActivity: "Hot springs and road-trip rest stop" },
  { name: "Ghasa", distanceKm: 37, mainActivity: "Kali Gandaki valley village stop" },
  { name: "Ghami", distanceKm: 80, mainActivity: "Upper Mustang village and red cliff scenery" },
  { name: "Tsarang", distanceKm: 92, mainActivity: "Monastery and palace heritage route" },
  { name: "Damodar Kunda", distanceKm: 120, mainActivity: "High-altitude pilgrimage extension" },
];

module.exports = { locationSeeds, listingSeeds, nearbyRecommendations };
