const tripPackageSeeds = [
  {
    title: "Lower Mustang Culture and Muktinath Trail",
    slug: "lower-mustang-culture-muktinath-trail",
    shortDescription: "A practical 4-day Mustang trip covering Jomsom, Marpha, Kagbeni, Muktinath, Dhumba Lake, and village culture.",
    description:
      "Built for travelers who want Mustang's signature culture without committing to the longer Upper Mustang route. This package combines Thakali food, apple village charm, sacred Muktinath, Kagbeni's old lanes, and the dry Kali Gandaki valley landscape.",
    location: "Mustang",
    region: "Gandaki Province",
    pickupCity: "Pokhara / Jomsom",
    dropoffCity: "Pokhara / Jomsom",
    startDate: "2026-10-11",
    endDate: "2026-10-14",
    basePrice: 28500,
    discountPrice: 26500,
    rating: 4.8,
    currency: "NPR",
    capacity: 10,
    minGuests: 2,
    maxGuests: 10,
    coverImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1400&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
    ],
    videoUrl: "",
    included: [
      "3 nights lodge or hotel stay",
      "Daily breakfast",
      "Jomsom orientation",
      "Marpha village walk",
      "Kagbeni heritage walk",
      "Muktinath temple transfer",
      "Dhumba Lake short hike",
      "Local coordinator support",
    ],
    excluded: ["Lunch and dinner", "Flights or private jeep from Pokhara unless selected", "Travel insurance", "Personal offerings"],
    highlights: ["Muktinath Temple", "Kagbeni old village", "Marpha apple culture", "Dhumba Lake"],
    bestSeason: "March to May and September to November",
    difficulty: "Easy to Moderate",
    tripType: "Culture and Pilgrimage",
    cancellationPolicy: "Free cancellation up to 10 days before departure. 35% charge within 72 hours due to lodge and jeep holds.",
    paymentPolicy: "35% advance payment required to confirm rooms and transfers. Remaining balance due before Day 2 departure.",
    faqs: [
      {
        question: "Is this suitable for first-time Mustang visitors?",
        answer: "Yes. It focuses on the accessible lower Mustang route and avoids the longer restricted Upper Mustang section.",
      },
      {
        question: "Is altitude a concern?",
        answer: "The route is high and dry, so warm clothing and steady pacing are recommended, but the itinerary is not technically difficult.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Arrival in Jomsom and wind valley orientation",
        summary: "Arrive in Jomsom, settle in, walk the bazaar and Kali Gandaki riverside, and enjoy a classic Thakali meal.",
        hotelTitle: "Hotel Oms Home Jomsom",
        meals: ["Welcome tea"],
        transport: "Airport pickup or jeep arrival support",
        altitude: "2,743 m",
        notes: "Afternoon winds can be strong in Jomsom, so keep a windproof layer ready.",
        image: "",
        activities: [
          { listingTitle: "Jomsom Wind Valley Orientation", notes: "Gentle first-day orientation." },
          { listingTitle: "Jomsom Thakali Kitchen", notes: "Suggested dinner stop." },
        ],
      },
      {
        dayNumber: 2,
        title: "Marpha, Dhumba Lake, and local food",
        summary: "Visit Marpha's whitewashed lanes and apple culture, then take a short scenic hike to Dhumba Lake.",
        hotelTitle: "Hotel Oms Home Jomsom",
        meals: ["Breakfast"],
        transport: "Private local jeep",
        altitude: "2,650 m to 2,830 m",
        notes: "Good walking shoes and sun protection are recommended.",
        image: "",
        activities: [
          { listingTitle: "Marpha Apple Village Walk", notes: "Apple village and monastery-side walk." },
          { listingTitle: "Dhumba Lake Short Hike", notes: "Calm lake stop above Jomsom." },
        ],
      },
      {
        dayNumber: 3,
        title: "Kagbeni and Muktinath",
        summary: "Explore Kagbeni's old village, continue to Muktinath, and return through the dry valley landscape.",
        hotelTitle: "Hotel Yac Donalds Kagbeni",
        meals: ["Breakfast"],
        transport: "Private local jeep",
        altitude: "2,800 m to 3,800 m",
        notes: "Carry warm layers for Muktinath and move slowly at temple altitude.",
        image: "",
        activities: [
          { listingTitle: "Kagbeni Old Village Heritage Walk", notes: "Old settlement and monastery-side lanes." },
          { listingTitle: "Muktinath Temple Darshan Transfer", notes: "Temple-focused transfer and orientation." },
        ],
      },
      {
        dayNumber: 4,
        title: "Jharkot stop and departure",
        summary: "Visit Jharkot monastery area on the way back and complete departure from Jomsom.",
        hotelTitle: "Hotel Yac Donalds Kagbeni",
        meals: ["Breakfast"],
        transport: "Departure jeep or airport transfer",
        altitude: "2,743 m",
        notes: "Flight schedules from Jomsom are weather-sensitive.",
        image: "",
        activities: [{ listingTitle: "Jharkot Monastery Cultural Stop", notes: "Final monastery and village stop." }],
      },
    ],
    addOnTitles: ["Lupra Bon Village Experience", "Chhusang Red Cliff Jeep Stop", "Marpha Apple Garden Restaurant"],
    isFeatured: true,
    isActive: true,
  },
  {
    title: "Upper Mustang Walled Kingdom Expedition",
    slug: "upper-mustang-walled-kingdom-expedition",
    shortDescription: "A premium Upper Mustang culture route with Lo Manthang, Chhoser caves, red cliffs, villages, and jeep-supported exploration.",
    description:
      "A deeper Mustang journey for culture lovers and adventure road travelers. This package follows the trans-Himalayan route toward Lo Manthang, combining dramatic cliffs, Tibetan-influenced villages, monasteries, sky caves, and the rare atmosphere of Nepal's old walled kingdom.",
    location: "Mustang",
    region: "Upper Mustang, Gandaki Province",
    pickupCity: "Jomsom",
    dropoffCity: "Jomsom",
    startDate: "2026-09-20",
    endDate: "2026-09-25",
    basePrice: 68500,
    discountPrice: 64000,
    rating: 4.9,
    currency: "NPR",
    capacity: 8,
    minGuests: 2,
    maxGuests: 8,
    coverImage: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1400&q=80",
    galleryImages: ["https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1200&q=80"],
    videoUrl: "",
    included: [
      "5 nights lodge stay",
      "Daily breakfast",
      "Upper Mustang jeep support",
      "Lo Manthang cultural walk",
      "Chhoser cave exploration",
      "Kagbeni and Chhusang stops",
      "Local guide support",
    ],
    excluded: ["Restricted area permits", "Lunch and dinner", "Travel insurance", "Emergency evacuation", "Flights to or from Jomsom"],
    highlights: ["Lo Manthang", "Chhoser sky caves", "Kagbeni gateway", "Upper Mustang desert landscapes"],
    bestSeason: "April to November",
    difficulty: "Moderate",
    tripType: "Upper Mustang Culture Expedition",
    cancellationPolicy: "Free cancellation up to 15 days before departure. Permit and lodge costs may be non-refundable once processed.",
    paymentPolicy: "50% advance payment required due to jeep, lodge, and permit coordination.",
    faqs: [
      {
        question: "Are permits included?",
        answer: "Restricted area permits are listed separately because prices and eligibility can vary. The team can coordinate them as an add-on.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Jomsom to Kagbeni and Chhusang",
        summary: "Start from Jomsom, explore Kagbeni, then continue toward Chhusang's red cliffs and river valley.",
        hotelTitle: "Hotel Yac Donalds Kagbeni",
        meals: ["Breakfast"],
        transport: "Private Upper Mustang jeep",
        altitude: "2,800 m to 3,000 m",
        notes: "Road conditions vary by season.",
        image: "",
        activities: [
          { listingTitle: "Kagbeni Old Village Heritage Walk", notes: "Gateway village walk." },
          { listingTitle: "Chhusang Red Cliff Jeep Stop", notes: "Scenic cliff and valley stop." },
        ],
      },
      {
        dayNumber: 2,
        title: "Chhusang to Lo Manthang route",
        summary: "Drive through high desert terrain, village stops, and wide valley viewpoints toward Lo Manthang.",
        hotelTitle: "Lo Manthang Heritage Lodge",
        meals: ["Breakfast"],
        transport: "Private Upper Mustang jeep",
        altitude: "3,800 m",
        notes: "Long road day with frequent photo and tea stops.",
        image: "",
        activities: [{ listingTitle: "Lo Manthang Tea House Cafe", notes: "Warm arrival stop in Lo Manthang." }],
      },
      {
        dayNumber: 3,
        title: "Lo Manthang walled city",
        summary: "Explore Lo Manthang's walled settlement, monastery areas, old alleys, and viewpoint edges.",
        hotelTitle: "Lo Manthang Heritage Lodge",
        meals: ["Breakfast"],
        transport: "Local walk and short jeep support",
        altitude: "3,840 m",
        notes: "A slower day for cultural depth and acclimatization.",
        image: "",
        activities: [{ listingTitle: "Lo Manthang Walled City Walk", notes: "Core cultural walk of the package." }],
      },
      {
        dayNumber: 4,
        title: "Chhoser cave heritage",
        summary: "Visit Chhoser cave area and return to Lo Manthang for a quiet evening.",
        hotelTitle: "Lo Manthang Heritage Lodge",
        meals: ["Breakfast"],
        transport: "Local jeep",
        altitude: "3,900 m",
        notes: "Cave access may require careful steps and basic fitness.",
        image: "",
        activities: [{ listingTitle: "Chhoser Sky Cave Exploration", notes: "Ancient cave and cliff heritage." }],
      },
      {
        dayNumber: 5,
        title: "Return toward lower Mustang",
        summary: "Drive back through the desert valleys with flexible photo stops and overnight near Kagbeni or Jomsom.",
        hotelTitle: "Hotel Oms Home Jomsom",
        meals: ["Breakfast"],
        transport: "Private jeep",
        altitude: "2,743 m",
        notes: "A long descent road day.",
        image: "",
        activities: [],
      },
      {
        dayNumber: 6,
        title: "Departure from Jomsom",
        summary: "Final breakfast, airport or jeep departure support, and optional Marpha stop if traveling by road.",
        hotelTitle: "Hotel Oms Home Jomsom",
        meals: ["Breakfast"],
        transport: "Departure support",
        altitude: "2,743 m",
        notes: "Weather can affect morning flights.",
        image: "",
        activities: [{ listingTitle: "Marpha Apple Village Walk", notes: "Optional stop for road departures." }],
      },
    ],
    addOnTitles: ["Muktinath Temple Darshan Transfer", "Lupra Bon Village Experience", "Lo Manthang Tea House Cafe"],
    isFeatured: true,
    isActive: true,
  },
  {
    title: "Mustang Pilgrimage and Family Road Trip",
    slug: "mustang-pilgrimage-family-road-trip",
    shortDescription: "A family-friendly Mustang road package focused on Muktinath, Kagbeni, Marpha, Jomsom, and comfortable pacing.",
    description:
      "Designed for families, pilgrims, and mixed-age groups who want a meaningful Mustang trip with careful pacing, practical hotels, temple timing support, and scenic stops without heavy trekking.",
    location: "Mustang",
    region: "Gandaki Province",
    pickupCity: "Pokhara",
    dropoffCity: "Pokhara",
    startDate: "2026-11-05",
    endDate: "2026-11-08",
    basePrice: 36000,
    discountPrice: 33500,
    rating: 4.7,
    currency: "NPR",
    capacity: 12,
    minGuests: 3,
    maxGuests: 12,
    coverImage: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1400&q=80",
    galleryImages: [],
    videoUrl: "",
    included: ["3 nights hotel or lodge stay", "Daily breakfast", "Private jeep from Pokhara", "Muktinath darshan support", "Kagbeni and Marpha stops", "Family coordinator support"],
    excluded: ["Lunch and dinner", "Personal offerings", "Travel insurance", "Extra heating charges if required by lodge"],
    highlights: ["Muktinath darshan", "Private jeep comfort", "Marpha apple village", "Kagbeni heritage"],
    bestSeason: "March to May and September to November",
    difficulty: "Easy",
    tripType: "Family Pilgrimage Road Trip",
    cancellationPolicy: "Free cancellation up to 10 days before departure. 30% charge within 72 hours.",
    paymentPolicy: "35% advance required for jeep and room confirmation.",
    faqs: [
      {
        question: "Is this suitable for senior family members?",
        answer: "Yes, but the route is high altitude. The itinerary avoids long trekking and uses jeep-supported movement.",
      },
    ],
    itineraryDays: [
      {
        dayNumber: 1,
        title: "Pokhara to Marpha or Jomsom",
        summary: "Begin the scenic road journey into Mustang with river valley views and a warm village arrival.",
        hotelTitle: "Paradise Guest House Marpha",
        meals: ["Welcome tea"],
        transport: "Private jeep",
        altitude: "2,650 m",
        notes: "Road day timing depends on traffic and weather.",
        image: "",
        activities: [{ listingTitle: "Marpha Apple Village Walk", notes: "Light evening village walk if arrival is early." }],
      },
      {
        dayNumber: 2,
        title: "Kagbeni and Muktinath darshan",
        summary: "Continue toward Kagbeni and Muktinath for the main pilgrimage day.",
        hotelTitle: "Muktinath Grand Hotel",
        meals: ["Breakfast"],
        transport: "Private jeep",
        altitude: "3,800 m",
        notes: "Carry warm clothes and move slowly near temple altitude.",
        image: "",
        activities: [
          { listingTitle: "Kagbeni Old Village Heritage Walk", notes: "Short cultural stop." },
          { listingTitle: "Muktinath Temple Darshan Transfer", notes: "Main pilgrimage activity." },
        ],
      },
      {
        dayNumber: 3,
        title: "Jharkot, Jomsom, and Dhumba Lake",
        summary: "Return through Jharkot and Jomsom, with an optional gentle lake walk.",
        hotelTitle: "Hotel Oms Home Jomsom",
        meals: ["Breakfast"],
        transport: "Private jeep",
        altitude: "2,743 m",
        notes: "Dhumba Lake can be skipped for senior travelers who prefer rest.",
        image: "",
        activities: [
          { listingTitle: "Jharkot Monastery Cultural Stop", notes: "Monastery-side stop." },
          { listingTitle: "Dhumba Lake Short Hike", notes: "Optional gentle walk." },
        ],
      },
      {
        dayNumber: 4,
        title: "Return to Pokhara",
        summary: "Drive back toward Pokhara with meal and photo stops along the Kali Gandaki route.",
        hotelTitle: "Hotel Oms Home Jomsom",
        meals: ["Breakfast"],
        transport: "Private jeep",
        altitude: "822 m at Pokhara",
        notes: "A long road day; keep snacks and water ready.",
        image: "",
        activities: [],
      },
    ],
    addOnTitles: ["Muktinath Pilgrim Bhojanalaya", "Jomsom Thakali Kitchen", "Dhumba Lake Tea Stop"],
    isFeatured: false,
    isActive: true,
  },
];

module.exports = { tripPackageSeeds };
