const mongoose = require("mongoose");

const locationSeeds = [
  {
    key: "pokhara",
    name: "Pokhara",
    province: "Gandaki",
    district: "Kaski",
    category: "Destination Hub",
    averageCost: 2500,
    latitude: 28.2096,
    longitude: 83.9856,
    description:
      "Pokhara is Nepal's leading leisure city, known for lakes, mountain views, adventure sports, temples, and easy access to short scenic getaways.",
    image: "",
    images: [],
  },
  {
    key: "phewa-lake",
    parentKey: "pokhara",
    name: "Phewa Lake",
    province: "Gandaki",
    district: "Kaski",
    category: "Lake",
    averageCost: 800,
    latitude: 28.2152,
    longitude: 83.9444,
    description:
      "Pokhara's iconic lake with boating, lakeside walks, sunrise reflections, and direct views toward the Annapurna range.",
    image: "",
    images: [],
  },
  {
    key: "tal-barahi-temple",
    parentKey: "pokhara",
    name: "Tal Barahi Temple",
    province: "Gandaki",
    district: "Kaski",
    category: "Temple",
    averageCost: 300,
    latitude: 28.2099,
    longitude: 83.9558,
    description:
      "A revered island temple in the middle of Phewa Lake, reached by short boat rides from Lakeside.",
    image: "",
    images: [],
  },
  {
    key: "sarangkot",
    parentKey: "pokhara",
    name: "Sarangkot",
    province: "Gandaki",
    district: "Kaski",
    category: "Viewpoint",
    averageCost: 1200,
    latitude: 28.2458,
    longitude: 83.9445,
    description:
      "A famous hilltop viewpoint above Pokhara for sunrise, paragliding launches, and wide Himalayan panoramas.",
    image: "",
    images: [],
  },
  {
    key: "world-peace-pagoda",
    parentKey: "pokhara",
    name: "World Peace Pagoda",
    province: "Gandaki",
    district: "Kaski",
    category: "Cultural",
    averageCost: 500,
    latitude: 28.2006,
    longitude: 83.944,
    description:
      "A white Buddhist stupa on a ridge above Phewa Lake with sweeping views across Pokhara Valley and the mountains.",
    image: "",
    images: [],
  },
  {
    key: "devis-fall",
    parentKey: "pokhara",
    name: "Devi's Fall",
    province: "Gandaki",
    district: "Kaski",
    category: "Nature",
    averageCost: 100,
    latitude: 28.1917,
    longitude: 83.9789,
    description:
      "A well-known waterfall where the water disappears into an underground tunnel, making it one of Pokhara's classic short stops.",
    image: "",
    images: [],
  },
  {
    key: "gupteshwor-mahadev-cave",
    parentKey: "pokhara",
    name: "Gupteshwor Mahadev Cave",
    province: "Gandaki",
    district: "Kaski",
    category: "Temple",
    averageCost: 150,
    latitude: 28.1913,
    longitude: 83.9792,
    description:
      "A sacred cave shrine close to Devi's Fall with limestone chambers and a Shiva temple inside.",
    image: "",
    images: [],
  },
  {
    key: "bindhyabasini-temple",
    parentKey: "pokhara",
    name: "Bindhyabasini Temple",
    province: "Gandaki",
    district: "Kaski",
    category: "Temple",
    averageCost: 200,
    latitude: 28.2377,
    longitude: 83.985,
    description:
      "One of Pokhara's oldest Hindu temples, set on a hill and visited for worship, festivals, and city views.",
    image: "",
    images: [],
  },
  {
    key: "international-mountain-museum",
    parentKey: "pokhara",
    name: "International Mountain Museum",
    province: "Gandaki",
    district: "Kaski",
    category: "Museum",
    averageCost: 500,
    latitude: 28.1971,
    longitude: 83.9856,
    description:
      "A museum focused on Himalayan geography, mountaineering history, and the cultures of Nepal's mountain communities.",
    image: "",
    images: [],
  },
  {
    key: "mahendra-cave",
    parentKey: "pokhara",
    name: "Mahendra Cave",
    province: "Gandaki",
    district: "Kaski",
    category: "Nature",
    averageCost: 150,
    latitude: 28.2658,
    longitude: 83.9839,
    description:
      "A limestone cave in Batulechaur known for dramatic rock formations and its cool underground route.",
    image: "",
    images: [],
  },
  {
    key: "bat-cave",
    parentKey: "pokhara",
    name: "Bat Cave",
    province: "Gandaki",
    district: "Kaski",
    category: "Nature",
    averageCost: 150,
    latitude: 28.2675,
    longitude: 83.9862,
    description:
      "A popular cave stop in north Pokhara where visitors can see bat colonies and try the narrow adventure exit.",
    image: "",
    images: [],
  },
  {
    key: "begnas-lake",
    parentKey: "pokhara",
    name: "Begnas Lake",
    province: "Gandaki",
    district: "Kaski",
    category: "Lake",
    averageCost: 700,
    latitude: 28.1734,
    longitude: 84.0961,
    description:
      "A quieter lake east of central Pokhara, ideal for day boating, relaxed lakeside meals, and peaceful views.",
    image: "",
    images: [],
  },
  {
    key: "pumdikot-shiva-statue",
    parentKey: "pokhara",
    name: "Pumdikot Shiva Statue",
    province: "Gandaki",
    district: "Kaski",
    category: "Cultural",
    averageCost: 300,
    latitude: 28.1839,
    longitude: 83.9316,
    description:
      "A rising hilltop attraction with a giant Shiva statue and broad views over Phewa Lake, Pokhara, and surrounding hills.",
    image: "",
    images: [],
  },
];

const listingSeeds = [
  {
    type: "activity",
    title: "Phewa Row Boat Ride",
    description: "Classic self-row or guided boating session on Phewa Lake.",
    location: { name: "Phewa Lake", address: "Lakeside Boat Station, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2152, lng: 83.9444 },
    pricePerUnit: 800,
    capacity: 4,
    amenities: ["Life jackets", "Boat rental", "Lakeside boarding"],
    rating: 4.8,
  },
  {
    type: "activity",
    title: "Phewa Sunset Boat Tour",
    description: "Golden-hour boating with calm lake reflections and mountain light.",
    location: { name: "Phewa Lake", address: "Lakeside Shore, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2148, lng: 83.9438 },
    pricePerUnit: 1500,
    capacity: 6,
    amenities: ["Life jackets", "Boatman", "Photo stop"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Lakeside Cycling Loop",
    description: "Easy cycling route along the Phewa waterfront and nearby streets.",
    location: { name: "Phewa Lake", address: "Lakeside, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2139, lng: 83.9452 },
    pricePerUnit: 600,
    capacity: 10,
    amenities: ["Bike rental", "Helmet", "Basic route support"],
    rating: 4.5,
  },

  {
    type: "activity",
    title: "Tal Barahi Temple Boat Transfer",
    description: "Short return transfer to the island shrine from Lakeside.",
    location: { name: "Tal Barahi Temple", address: "Phewa Lake Island, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2099, lng: 83.9558 },
    pricePerUnit: 300,
    capacity: 8,
    amenities: ["Shared boat", "Life jackets", "Temple drop-off"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Morning Temple Darshan",
    description: "Early worship visit to Tal Barahi before the peak crowd hours.",
    location: { name: "Tal Barahi Temple", address: "Tal Barahi Island, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2099, lng: 83.9558 },
    pricePerUnit: 200,
    capacity: 20,
    amenities: ["Temple access", "Prayer area", "Boat approach"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Temple and Lake Photo Tour",
    description: "Scenic short tour combining the temple stop with lake views.",
    location: { name: "Tal Barahi Temple", address: "Phewa Island Route, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2098, lng: 83.9554 },
    pricePerUnit: 1200,
    capacity: 6,
    amenities: ["Guide", "Boat ride", "Photo stop"],
    rating: 4.5,
  },

  {
    type: "activity",
    title: "Sarangkot Sunrise View Trip",
    description: "Early morning hilltop visit for Pokhara's most popular sunrise panorama.",
    location: { name: "Sarangkot", address: "Sarangkot Viewpoint, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2458, lng: 83.9445 },
    pricePerUnit: 500,
    capacity: 20,
    amenities: ["View deck", "Parking", "Sunrise timing"],
    rating: 4.9,
  },
  {
    type: "activity",
    title: "Sarangkot Tandem Paragliding",
    description: "Signature Pokhara adventure launching above the valley and Phewa Lake.",
    location: { name: "Sarangkot", address: "Paragliding Launch Site, Sarangkot", district: "Kaski", province: "Gandaki", lat: 28.2472, lng: 83.9436 },
    pricePerUnit: 8500,
    capacity: 1,
    amenities: ["Pilot", "Safety harness", "Transfer"],
    rating: 4.9,
  },
  {
    type: "activity",
    title: "Sarangkot Ridge Hike",
    description: "Short guided ridge hike with city, lake, and mountain views.",
    location: { name: "Sarangkot", address: "Sarangkot Trailhead, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2447, lng: 83.9461 },
    pricePerUnit: 1000,
    capacity: 12,
    amenities: ["Local guide", "Water break", "Scenic stops"],
    rating: 4.7,
  },

  {
    type: "activity",
    title: "Peace Pagoda Hike",
    description: "Guided uphill walk to the stupa from the lakeside side of Pokhara.",
    location: { name: "World Peace Pagoda", address: "Shanti Stupa Trail, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2006, lng: 83.944 },
    pricePerUnit: 1000,
    capacity: 12,
    amenities: ["Guide", "Water stop", "Trail support"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Peace Pagoda Sunset Session",
    description: "Evening viewpoint visit with excellent lake and valley light.",
    location: { name: "World Peace Pagoda", address: "World Peace Pagoda, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2006, lng: 83.944 },
    pricePerUnit: 300,
    capacity: 25,
    amenities: ["View terrace", "Photo stop", "Sunset slot"],
    rating: 4.8,
  },
  {
    type: "activity",
    title: "Peace Pagoda Cultural Tour",
    description: "Short guided cultural explanation of the pagoda and its symbolism.",
    location: { name: "World Peace Pagoda", address: "Shanti Stupa Complex, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2004, lng: 83.9442 },
    pricePerUnit: 1200,
    capacity: 10,
    amenities: ["Guide", "History briefing", "Viewpoint access"],
    rating: 4.6,
  },

  {
    type: "activity",
    title: "Devi's Fall Entry Visit",
    description: "A quick waterfall stop at one of Pokhara's most visited natural landmarks.",
    location: { name: "Devi's Fall", address: "Chhorepatan, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.1917, lng: 83.9789 },
    pricePerUnit: 100,
    capacity: 30,
    amenities: ["Entry gate", "View area", "Nearby shops"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Devi's Fall and Cave Combo Walk",
    description: "Easy paired visit to Devi's Fall and Gupteshwor Mahadev Cave.",
    location: { name: "Devi's Fall", address: "Chhorepatan Tourist Area, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.1915, lng: 83.9791 },
    pricePerUnit: 300,
    capacity: 15,
    amenities: ["Walk route", "Guide optional", "Combo stop"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Waterfall Photo Stop",
    description: "Short scenic photo break for casual city tours.",
    location: { name: "Devi's Fall", address: "Devi's Fall Gate, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.1919, lng: 83.9787 },
    pricePerUnit: 250,
    capacity: 10,
    amenities: ["Photo points", "Guide", "Nearby parking"],
    rating: 4.3,
  },

  {
    type: "activity",
    title: "Gupteshwor Cave Exploration",
    description: "Explore the cave passages and lower chamber viewpoint.",
    location: { name: "Gupteshwor Mahadev Cave", address: "Chhorepatan, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.1913, lng: 83.9792 },
    pricePerUnit: 150,
    capacity: 15,
    amenities: ["Cave access", "Stairs", "Basic lighting"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Gupteshwor Shiva Shrine Visit",
    description: "Sacred cave temple visit for cultural and spiritual travelers.",
    location: { name: "Gupteshwor Mahadev Cave", address: "Inside Gupteshwor Cave, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.1911, lng: 83.9793 },
    pricePerUnit: 200,
    capacity: 20,
    amenities: ["Temple access", "Prayer area", "Cave route"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Gupteshwor Guided Combo Tour",
    description: "Half-day guide service linking cave visit with nearby attractions.",
    location: { name: "Gupteshwor Mahadev Cave", address: "Chhorepatan Area, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.1914, lng: 83.9794 },
    pricePerUnit: 700,
    capacity: 8,
    amenities: ["Guide", "Route coordination", "Nearby stop support"],
    rating: 4.5,
  },

  {
    type: "activity",
    title: "Bindhyabasini Temple Darshan",
    description: "Short devotional temple stop in north Pokhara.",
    location: { name: "Bindhyabasini Temple", address: "Miruwa, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2377, lng: 83.985 },
    pricePerUnit: 100,
    capacity: 30,
    amenities: ["Temple access", "Prayer area", "Hilltop compound"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Bindhyabasini Festival Culture Visit",
    description: "Guided look at local worship traditions and temple life.",
    location: { name: "Bindhyabasini Temple", address: "Bindhyabasini Complex, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2375, lng: 83.9851 },
    pricePerUnit: 300,
    capacity: 20,
    amenities: ["Guide", "Temple briefing", "Local context"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Pokhara Temple Circuit",
    description: "Temple-focused city route starting from Bindhyabasini.",
    location: { name: "Bindhyabasini Temple", address: "Bindhyabasini Start Point, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2378, lng: 83.9852 },
    pricePerUnit: 1200,
    capacity: 10,
    amenities: ["Guide", "Flexible route", "Cultural stops"],
    rating: 4.5,
  },

  {
    type: "activity",
    title: "Mountain Museum Entry Tour",
    description: "Entry and self-paced museum visit covering Himalayan history.",
    location: { name: "International Mountain Museum", address: "Ratopahiro, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.1971, lng: 83.9856 },
    pricePerUnit: 500,
    capacity: 25,
    amenities: ["Gallery access", "Restrooms", "Museum grounds"],
    rating: 4.6,
  },
  {
    type: "activity",
    title: "Himalayan Culture Walkthrough",
    description: "Guided exhibit interpretation focused on mountain communities.",
    location: { name: "International Mountain Museum", address: "Museum Hall, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.197, lng: 83.9854 },
    pricePerUnit: 900,
    capacity: 12,
    amenities: ["Guide", "Exhibit briefing", "Indoor access"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Museum Educational Group Visit",
    description: "Group-oriented educational stop for students and organized tours.",
    location: { name: "International Mountain Museum", address: "Museum Complex, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.1972, lng: 83.9858 },
    pricePerUnit: 1200,
    capacity: 30,
    amenities: ["Group support", "Exhibits", "Outdoor area"],
    rating: 4.4,
  },

  {
    type: "activity",
    title: "Mahendra Cave Entry Visit",
    description: "Short underground visit through a classic limestone cave route.",
    location: { name: "Mahendra Cave", address: "Batulechaur, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2658, lng: 83.9839 },
    pricePerUnit: 150,
    capacity: 20,
    amenities: ["Cave entry", "Walk route", "Basic lighting"],
    rating: 4.3,
  },
  {
    type: "activity",
    title: "Mahendra Cave Nature Walk",
    description: "Simple guided walk around the cave zone and nearby greenery.",
    location: { name: "Mahendra Cave", address: "Mahendra Cave Area, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2654, lng: 83.9843 },
    pricePerUnit: 500,
    capacity: 10,
    amenities: ["Guide", "Short trail", "Nature stop"],
    rating: 4.2,
  },
  {
    type: "activity",
    title: "Mahendra and Bat Cave Combo",
    description: "Twin-cave short tour in north Pokhara.",
    location: { name: "Mahendra Cave", address: "Batulechaur Cave Route, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2661, lng: 83.9844 },
    pricePerUnit: 700,
    capacity: 8,
    amenities: ["Guide", "Combo route", "Short transfer"],
    rating: 4.4,
  },

  {
    type: "activity",
    title: "Bat Cave Entry",
    description: "Visit the cave chambers where bats are often visible overhead.",
    location: { name: "Bat Cave", address: "Batulechaur, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2675, lng: 83.9862 },
    pricePerUnit: 150,
    capacity: 20,
    amenities: ["Cave access", "Viewing area", "Basic lighting"],
    rating: 4.3,
  },
  {
    type: "activity",
    title: "Bat Cave Adventure Exit",
    description: "For adventurous visitors who want to try the narrow cave exit.",
    location: { name: "Bat Cave", address: "Bat Cave Inner Route, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2674, lng: 83.9864 },
    pricePerUnit: 250,
    capacity: 6,
    amenities: ["Guide", "Safety briefing", "Adventure route"],
    rating: 4.4,
  },
  {
    type: "activity",
    title: "Bat Cave Combo Tour",
    description: "Combined cave route linked with Mahendra Cave nearby.",
    location: { name: "Bat Cave", address: "Batulechaur Combo Route, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2672, lng: 83.986 },
    pricePerUnit: 700,
    capacity: 8,
    amenities: ["Guide", "Combo access", "Short transfer"],
    rating: 4.4,
  },

  {
    type: "activity",
    title: "Begnas Boating Session",
    description: "Quiet lake boating away from the busier Phewa shoreline.",
    location: { name: "Begnas Lake", address: "Begnas Lakeside, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.1734, lng: 84.0961 },
    pricePerUnit: 700,
    capacity: 5,
    amenities: ["Life jackets", "Boat rental", "Lakeside boarding"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Begnas Picnic Day",
    description: "Relaxed day-use outing by the lake with local food stops nearby.",
    location: { name: "Begnas Lake", address: "Begnas Shoreline, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.1731, lng: 84.0958 },
    pricePerUnit: 500,
    capacity: 15,
    amenities: ["Open space", "Local food nearby", "Waterfront seating"],
    rating: 4.5,
  },
  {
    type: "activity",
    title: "Begnas Fishing Experience",
    description: "Casual small-group fishing experience on the quieter side of Pokhara.",
    location: { name: "Begnas Lake", address: "Begnas Fishing Point, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.1728, lng: 84.0965 },
    pricePerUnit: 1500,
    capacity: 4,
    amenities: ["Basic gear", "Local support", "Lake access"],
    rating: 4.4,
  },

  {
    type: "activity",
    title: "Pumdikot Shiva Statue Visit",
    description: "Short hilltop visit to the statue complex and viewpoint.",
    location: { name: "Pumdikot Shiva Statue", address: "Pumdikot Hill, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.1839, lng: 83.9316 },
    pricePerUnit: 300,
    capacity: 25,
    amenities: ["View deck", "Temple area", "Parking"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Pumdikot Viewpoint Photo Stop",
    description: "A short scenic stop for city, lake, and hill panoramas.",
    location: { name: "Pumdikot Shiva Statue", address: "Pumdikot View Area, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.1841, lng: 83.9311 },
    pricePerUnit: 400,
    capacity: 10,
    amenities: ["Photo point", "Scenic deck", "Short access path"],
    rating: 4.7,
  },
  {
    type: "activity",
    title: "Pumdikot Half-Day Tour",
    description: "A half-day scenic route covering the statue complex and surrounding hill views.",
    location: { name: "Pumdikot Shiva Statue", address: "Pumdikot Route, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.1843, lng: 83.9321 },
    pricePerUnit: 1800,
    capacity: 8,
    amenities: ["Guide", "Transport", "Scenic stops"],
    rating: 4.6,
  },

  {
    type: "hotel",
    title: "Hotel Barahi",
    description: "A central Lakeside stay with easy access to Phewa Lake and major Pokhara tourist routes.",
    location: { name: "Phewa Lake", address: "Lakeside, near Phewa Lake, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2109, lng: 83.9591 },
    pricePerUnit: 6500,
    capacity: 2,
    amenities: ["Pool", "Restaurant", "Wi-Fi", "Airport transfer"],
    rating: 4.5,
  },
  {
    type: "hotel",
    title: "Temple Tree Resort and Spa",
    description: "An upscale resort-style property close to the main Lakeside zone.",
    location: { name: "Tal Barahi Temple", address: "Gaurighat, near Tal Barahi boat access, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2065, lng: 83.9583 },
    pricePerUnit: 9000,
    capacity: 2,
    amenities: ["Spa", "Pool", "Garden", "Restaurant"],
    rating: 4.7,
  },
  {
    type: "hotel",
    title: "Waterfront Resort by KGH Group",
    description: "A quieter lake-facing stay suitable for couples and scenic holidays.",
    location: { name: "Sarangkot", address: "Sedi Height, on the Sarangkot side of Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2284, lng: 83.9578 },
    pricePerUnit: 8000,
    capacity: 2,
    amenities: ["Pool", "Restaurant", "Lake view", "Parking"],
    rating: 4.6,
  },
  {
    type: "hotel",
    title: "Fish Tail Lodge",
    description: "A known Pokhara stay near the lake with historic appeal and garden surroundings.",
    location: { name: "World Peace Pagoda", address: "Lakeside South, convenient for World Peace Pagoda access", district: "Kaski", province: "Gandaki", lat: 28.2047, lng: 83.9575 },
    pricePerUnit: 11000,
    capacity: 2,
    amenities: ["Garden", "Restaurant", "Shuttle", "Lake access"],
    rating: 4.6,
  },
  {
    type: "hotel",
    title: "Atithi Resort and Spa",
    description: "A comfortable upper-midscale stay for family and leisure travelers in Pokhara.",
    location: { name: "Devi's Fall", address: "Shanti Patan, close to Devi's Fall and Gupteshwor area", district: "Kaski", province: "Gandaki", lat: 28.1985, lng: 83.9696 },
    pricePerUnit: 7000,
    capacity: 2,
    amenities: ["Spa", "Pool", "Breakfast", "Wi-Fi"],
    rating: 4.4,
  },

  {
    type: "cafe",
    title: "Himalayan Java Coffee Pokhara",
    description: "Reliable coffee stop in Lakeside for casual meetings and rest breaks.",
    location: { name: "Phewa Lake", address: "Lakeside, by the Phewa promenade, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2101, lng: 83.9579 },
    pricePerUnit: 450,
    capacity: 30,
    amenities: ["Coffee", "Bakery", "Wi-Fi"],
    rating: 4.5,
  },
  {
    type: "cafe",
    title: "Fresh Elements Cafe",
    description: "Popular brunch and coffee spot for travelers staying around Lakeside.",
    location: { name: "Tal Barahi Temple", address: "Lakeside-6, near the Tal Barahi boat area, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2106, lng: 83.9588 },
    pricePerUnit: 600,
    capacity: 24,
    amenities: ["Coffee", "Breakfast", "Healthy menu"],
    rating: 4.6,
  },
  {
    type: "cafe",
    title: "Cafe Concerto",
    description: "A cozy garden-style bakery cafe known for desserts and relaxed seating.",
    location: { name: "World Peace Pagoda", address: "Lakeside Road, convenient for Peace Pagoda visitors, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2094, lng: 83.9596 },
    pricePerUnit: 550,
    capacity: 22,
    amenities: ["Bakery", "Coffee", "Garden seating"],
    rating: 4.4,
  },

  {
    type: "restaurant",
    title: "Moondance Restaurant and Bar",
    description: "A long-running tourist favorite serving Nepali, Indian, and continental dishes.",
    location: { name: "Phewa Lake", address: "Lakeside, near Phewa Lake, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2116, lng: 83.9581 },
    pricePerUnit: 1200,
    capacity: 40,
    amenities: ["Indoor seating", "Bar", "Family-friendly"],
    rating: 4.5,
  },
  {
    type: "restaurant",
    title: "OR2K Pokhara",
    description: "A well-liked vegetarian-friendly restaurant with Middle Eastern and fusion options.",
    location: { name: "Tal Barahi Temple", address: "Lakeside, near Tal Barahi access, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2108, lng: 83.959 },
    pricePerUnit: 1000,
    capacity: 30,
    amenities: ["Vegetarian options", "Indoor seating", "Travel-friendly"],
    rating: 4.4,
  },
  {
    type: "restaurant",
    title: "Rosemary Kitchen",
    description: "A warm, traveler-friendly restaurant with Nepali and continental meal options.",
    location: { name: "Devi's Fall", address: "Lakeside route popular with Devi's Fall day visitors, Pokhara", district: "Kaski", province: "Gandaki", lat: 28.2098, lng: 83.9583 },
    pricePerUnit: 1100,
    capacity: 28,
    amenities: ["Indoor seating", "Local cuisine", "Tourist-friendly service"],
    rating: 4.6,
  },
];

const nearbyRecommendations = [
  { name: "Dhampus", distanceKm: 22, mainActivity: "Village hiking and mountain-view trekking" },
  { name: "Kahun Danda", distanceKm: 12, mainActivity: "Viewpoint hike and city panorama" },
  { name: "Naudanda", distanceKm: 18, mainActivity: "Hill walk and sunset viewpoint" },
  { name: "Australian Camp", distanceKm: 28, mainActivity: "Short ridge trek and sunrise walk" },
  { name: "Panchase", distanceKm: 35, mainActivity: "Hiking and scenic hill excursion" },
];

function buildPokharaSeed(createdBy) {
  if (!createdBy) {
    throw new Error("buildPokharaSeed(createdBy) requires a valid user id for Listing.createdBy");
  }

  const locationIdMap = new Map();

  const locations = locationSeeds.map((item) => {
    const _id = new mongoose.Types.ObjectId();
    locationIdMap.set(item.key, _id);
    return {
      _id,
      name: item.name,
      province: item.province,
      district: item.district,
      parentLocationId: null,
      description: item.description,
      category: item.category,
      averageCost: item.averageCost,
      image: item.image || "",
      images: item.images || [],
      latitude: item.latitude,
      longitude: item.longitude,
    };
  });

  for (const location of locations) {
    const seed = locationSeeds.find((item) => item.name === location.name);
    if (seed?.parentKey) {
      location.parentLocationId = locationIdMap.get(seed.parentKey) || null;
    }
  }

  const listings = listingSeeds.map((item) => ({
    type: item.type,
    title: item.title,
    description: item.description,
    location: item.location,
    pricePerUnit: item.pricePerUnit,
    capacity: item.capacity,
    amenities: item.amenities,
    photos: item.photos || [],
    rating: item.rating,
    reviews: [],
    isActive: true,
    createdBy,
  }));

  return {
    locations,
    listings,
    nearbyRecommendations,
  };
}

module.exports = {
  locationSeeds,
  listingSeeds,
  nearbyRecommendations,
  buildPokharaSeed,
};
